-- Repeatable baseline seed for non-production environments
MERGE INTO REF_DON_VI d USING (SELECT 2001 ID, 'H05' MA_DON_VI, 'Cuc CNTT H05' TEN_DON_VI, 'H05' TEN_VIET_TAT, CAST(NULL AS NUMBER) PARENT_ID, 'CUC' CAP_DON_VI, 'http://h05-noibo.local' WEBSITE_NOI_BO, 'https://h05.bocongan.gov.vn' WEBSITE_INTERNET, 1200 TONG_BIEN_CHE FROM dual) s
ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET d.MA_DON_VI = s.MA_DON_VI, d.TEN_DON_VI = s.TEN_DON_VI, d.TEN_VIET_TAT = s.TEN_VIET_TAT, d.PARENT_ID = s.PARENT_ID, d.CAP_DON_VI = s.CAP_DON_VI, d.WEBSITE_NOI_BO = s.WEBSITE_NOI_BO, d.WEBSITE_INTERNET = s.WEBSITE_INTERNET, d.TONG_BIEN_CHE = s.TONG_BIEN_CHE, d.IS_ACTIVE = 1, d.DELETED_AT = NULL
WHEN NOT MATCHED THEN INSERT (ID, MA_DON_VI, TEN_DON_VI, TEN_VIET_TAT, PARENT_ID, CAP_DON_VI, WEBSITE_NOI_BO, WEBSITE_INTERNET, TONG_BIEN_CHE, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES (s.ID, s.MA_DON_VI, s.TEN_DON_VI, s.TEN_VIET_TAT, s.PARENT_ID, s.CAP_DON_VI, s.WEBSITE_NOI_BO, s.WEBSITE_INTERNET, s.TONG_BIEN_CHE, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO REF_DON_VI d USING (SELECT 2002 ID, 'CA_HN' MA_DON_VI, 'Cong an TP Ha Noi' TEN_DON_VI, 'CAHN' TEN_VIET_TAT, 2001 PARENT_ID, 'TINH' CAP_DON_VI, 'http://cahn-noibo.local' WEBSITE_NOI_BO, 'https://congan.hanoi.gov.vn' WEBSITE_INTERNET, 850 TONG_BIEN_CHE FROM dual) s
ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET d.MA_DON_VI = s.MA_DON_VI, d.TEN_DON_VI = s.TEN_DON_VI, d.TEN_VIET_TAT = s.TEN_VIET_TAT, d.PARENT_ID = s.PARENT_ID, d.CAP_DON_VI = s.CAP_DON_VI, d.WEBSITE_NOI_BO = s.WEBSITE_NOI_BO, d.WEBSITE_INTERNET = s.WEBSITE_INTERNET, d.TONG_BIEN_CHE = s.TONG_BIEN_CHE, d.IS_ACTIVE = 1, d.DELETED_AT = NULL
WHEN NOT MATCHED THEN INSERT (ID, MA_DON_VI, TEN_DON_VI, TEN_VIET_TAT, PARENT_ID, CAP_DON_VI, WEBSITE_NOI_BO, WEBSITE_INTERNET, TONG_BIEN_CHE, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES (s.ID, s.MA_DON_VI, s.TEN_DON_VI, s.TEN_VIET_TAT, s.PARENT_ID, s.CAP_DON_VI, s.WEBSITE_NOI_BO, s.WEBSITE_INTERNET, s.TONG_BIEN_CHE, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO REF_DON_VI d USING (SELECT 2003 ID, 'CA_DN' MA_DON_VI, 'Cong an TP Da Nang' TEN_DON_VI, 'CADN' TEN_VIET_TAT, 2001 PARENT_ID, 'TINH' CAP_DON_VI, 'http://cadn-noibo.local' WEBSITE_NOI_BO, 'https://congan.danang.gov.vn' WEBSITE_INTERNET, 640 TONG_BIEN_CHE FROM dual) s
ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET d.MA_DON_VI = s.MA_DON_VI, d.TEN_DON_VI = s.TEN_DON_VI, d.TEN_VIET_TAT = s.TEN_VIET_TAT, d.PARENT_ID = s.PARENT_ID, d.CAP_DON_VI = s.CAP_DON_VI, d.WEBSITE_NOI_BO = s.WEBSITE_NOI_BO, d.WEBSITE_INTERNET = s.WEBSITE_INTERNET, d.TONG_BIEN_CHE = s.TONG_BIEN_CHE, d.IS_ACTIVE = 1, d.DELETED_AT = NULL
WHEN NOT MATCHED THEN INSERT (ID, MA_DON_VI, TEN_DON_VI, TEN_VIET_TAT, PARENT_ID, CAP_DON_VI, WEBSITE_NOI_BO, WEBSITE_INTERNET, TONG_BIEN_CHE, IS_ACTIVE, CREATED_AT, UPDATED_AT) VALUES (s.ID, s.MA_DON_VI, s.TEN_DON_VI, s.TEN_VIET_TAT, s.PARENT_ID, s.CAP_DON_VI, s.WEBSITE_NOI_BO, s.WEBSITE_INTERNET, s.TONG_BIEN_CHE, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO RPT_KY_BAO_CAO d USING (SELECT 6001 ID, '2026Q1' KY_CODE, 2026 NAM, 1 QUY, 2 TRANG_THAI, DATE '2026-01-01' NGAY_BAT_DAU, DATE '2026-03-31' NGAY_KET_THUC, 'Ky bao cao dang mo cho test flow snapshot' GHI_CHU FROM dual) s
ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET d.KY_CODE = s.KY_CODE, d.NAM = s.NAM, d.QUY = s.QUY, d.TRANG_THAI = s.TRANG_THAI, d.NGAY_BAT_DAU = s.NGAY_BAT_DAU, d.NGAY_KET_THUC = s.NGAY_KET_THUC, d.GHI_CHU = s.GHI_CHU
WHEN NOT MATCHED THEN INSERT (ID, KY_CODE, NAM, QUY, TRANG_THAI, NGAY_BAT_DAU, NGAY_KET_THUC, GHI_CHU, CREATED_AT, UPDATED_AT) VALUES (s.ID, s.KY_CODE, s.NAM, s.QUY, s.TRANG_THAI, s.NGAY_BAT_DAU, s.NGAY_KET_THUC, s.GHI_CHU, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO RPT_KY_BAO_CAO d USING (SELECT 6002 ID, '2025Q4' KY_CODE, 2025 NAM, 4 QUY, 3 TRANG_THAI, DATE '2025-10-01' NGAY_BAT_DAU, DATE '2025-12-31' NGAY_KET_THUC, 'Ky bao cao da dong' GHI_CHU FROM dual) s
ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET d.KY_CODE = s.KY_CODE, d.NAM = s.NAM, d.QUY = s.QUY, d.TRANG_THAI = s.TRANG_THAI, d.NGAY_BAT_DAU = s.NGAY_BAT_DAU, d.NGAY_KET_THUC = s.NGAY_KET_THUC, d.GHI_CHU = s.GHI_CHU
WHEN NOT MATCHED THEN INSERT (ID, KY_CODE, NAM, QUY, TRANG_THAI, NGAY_BAT_DAU, NGAY_KET_THUC, GHI_CHU, CREATED_AT, UPDATED_AT) VALUES (s.ID, s.KY_CODE, s.NAM, s.QUY, s.TRANG_THAI, s.NGAY_BAT_DAU, s.NGAY_KET_THUC, s.GHI_CHU, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO RPT_KY_TRANG_THAI_DON_VI d USING (SELECT 7001 ID, 6001 KY_BAO_CAO_ID, 2002 DON_VI_ID, 1 TRANG_THAI FROM dual) s
ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET d.KY_BAO_CAO_ID = s.KY_BAO_CAO_ID, d.DON_VI_ID = s.DON_VI_ID, d.TRANG_THAI = s.TRANG_THAI
WHEN NOT MATCHED THEN INSERT (ID, KY_BAO_CAO_ID, DON_VI_ID, TRANG_THAI, CREATED_AT, UPDATED_AT) VALUES (s.ID, s.KY_BAO_CAO_ID, s.DON_VI_ID, s.TRANG_THAI, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO RPT_KY_TRANG_THAI_DON_VI d USING (SELECT 7002 ID, 6001 KY_BAO_CAO_ID, 2003 DON_VI_ID, 1 TRANG_THAI FROM dual) s
ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET d.KY_BAO_CAO_ID = s.KY_BAO_CAO_ID, d.DON_VI_ID = s.DON_VI_ID, d.TRANG_THAI = s.TRANG_THAI
WHEN NOT MATCHED THEN INSERT (ID, KY_BAO_CAO_ID, DON_VI_ID, TRANG_THAI, CREATED_AT, UPDATED_AT) VALUES (s.ID, s.KY_BAO_CAO_ID, s.DON_VI_ID, s.TRANG_THAI, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO RPT_KY_TRANG_THAI_DON_VI d USING (SELECT 7003 ID, 6002 KY_BAO_CAO_ID, 2002 DON_VI_ID, 3 TRANG_THAI FROM dual) s
ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET d.KY_BAO_CAO_ID = s.KY_BAO_CAO_ID, d.DON_VI_ID = s.DON_VI_ID, d.TRANG_THAI = s.TRANG_THAI
WHEN NOT MATCHED THEN INSERT (ID, KY_BAO_CAO_ID, DON_VI_ID, TRANG_THAI, CREATED_AT, UPDATED_AT) VALUES (s.ID, s.KY_BAO_CAO_ID, s.DON_VI_ID, s.TRANG_THAI, SYSTIMESTAMP, SYSTIMESTAMP);

-- ─── Mẫu báo cáo (RPT_MAU_BAO_CAO) ─────────────────────────────────────────
-- TAN_SUAT: 1=Tháng, 2=Quý, 3=Năm
-- Đây là danh sách mẫu gợi ý — admin có thể thêm/sửa qua UI sau khi hệ thống lên production.

-- KyCode tự sinh = {NAM}Q{Q}_{MA_MAU} | {NAM}T{MM}_{MA_MAU} | {NAM}_{MA_MAU}
-- Không cần KY_CODE_PREFIX riêng vì MA_MAU đã là prefix ngắn gọn, unique.

MERGE INTO RPT_MAU_BAO_CAO d USING (SELECT 8001 ID FROM dual) s ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET
    d.MA_MAU='NHAN_LUC', d.TEN_MAU='Báo cáo Nhân lực CNTT', d.TAN_SUAT=2, d.IS_ACTIVE=1,
    d.DANH_SACH_MODULE='["NHAN_LUC_CNTT","NANG_LUC_SO"]',
    d.MO_TA='Báo cáo tình hình nhân lực CNTT và năng lực số theo quý'
WHEN NOT MATCHED THEN INSERT (ID,MA_MAU,TEN_MAU,TAN_SUAT,IS_ACTIVE,DANH_SACH_MODULE,MO_TA,CREATED_AT,UPDATED_AT)
VALUES (8001,'NHAN_LUC','Báo cáo Nhân lực CNTT',2,1,'["NHAN_LUC_CNTT","NANG_LUC_SO"]','Báo cáo tình hình nhân lực CNTT và năng lực số theo quý',SYSTIMESTAMP,SYSTIMESTAMP);

MERGE INTO RPT_MAU_BAO_CAO d USING (SELECT 8002 ID FROM dual) s ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET
    d.MA_MAU='DAO_TAO', d.TEN_MAU='Báo cáo Đào tạo', d.TAN_SUAT=2, d.IS_ACTIVE=1,
    d.DANH_SACH_MODULE='["DAO_TAO_BOI_DUONG","DAO_TAO_HOC_VIEN"]',
    d.MO_TA='Báo cáo tổng hợp các hình thức đào tạo CNTT theo quý'
WHEN NOT MATCHED THEN INSERT (ID,MA_MAU,TEN_MAU,TAN_SUAT,IS_ACTIVE,DANH_SACH_MODULE,MO_TA,CREATED_AT,UPDATED_AT)
VALUES (8002,'DAO_TAO','Báo cáo Đào tạo',2,1,'["DAO_TAO_BOI_DUONG","DAO_TAO_HOC_VIEN"]','Báo cáo tổng hợp các hình thức đào tạo CNTT theo quý',SYSTIMESTAMP,SYSTIMESTAMP);

MERGE INTO RPT_MAU_BAO_CAO d USING (SELECT 8003 ID FROM dual) s ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET
    d.MA_MAU='HA_TANG', d.TEN_MAU='Báo cáo Hạ tầng CNTT', d.TAN_SUAT=3, d.IS_ACTIVE=1,
    d.DANH_SACH_MODULE='["THIET_BI_CNTT","HA_TANG_MANG","HE_THONG_THONG_TIN","HTTT_TIEU_CHUAN"]',
    d.MO_TA='Báo cáo thực trạng hạ tầng, thiết bị và hệ thống thông tin theo năm'
WHEN NOT MATCHED THEN INSERT (ID,MA_MAU,TEN_MAU,TAN_SUAT,IS_ACTIVE,DANH_SACH_MODULE,MO_TA,CREATED_AT,UPDATED_AT)
VALUES (8003,'HA_TANG','Báo cáo Hạ tầng CNTT',3,1,'["THIET_BI_CNTT","HA_TANG_MANG","HE_THONG_THONG_TIN","HTTT_TIEU_CHUAN"]','Báo cáo thực trạng hạ tầng, thiết bị và hệ thống thông tin theo năm',SYSTIMESTAMP,SYSTIMESTAMP);

MERGE INTO RPT_MAU_BAO_CAO d USING (SELECT 8004 ID FROM dual) s ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET
    d.MA_MAU='DU_AN', d.TEN_MAU='Báo cáo Dự án CNTT', d.TAN_SUAT=2, d.IS_ACTIVE=1,
    d.DANH_SACH_MODULE='["DU_AN_CNTT"]',
    d.MO_TA='Báo cáo tiến độ và tình trạng các dự án CNTT theo quý'
WHEN NOT MATCHED THEN INSERT (ID,MA_MAU,TEN_MAU,TAN_SUAT,IS_ACTIVE,DANH_SACH_MODULE,MO_TA,CREATED_AT,UPDATED_AT)
VALUES (8004,'DU_AN','Báo cáo Dự án CNTT',2,1,'["DU_AN_CNTT"]','Báo cáo tiến độ và tình trạng các dự án CNTT theo quý',SYSTIMESTAMP,SYSTIMESTAMP);

MERGE INTO RPT_MAU_BAO_CAO d USING (SELECT 8005 ID FROM dual) s ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET
    d.MA_MAU='ATTT', d.TEN_MAU='Báo cáo An toàn thông tin', d.TAN_SUAT=2, d.IS_ACTIVE=1,
    d.DANH_SACH_MODULE='["GIAM_SAT_SOC","GIAM_SAT_NOC","ATTT_GIAI_PHAP","ATTT_HTTT_VAN_HANH","ATTT_HTTT_DAU_TU"]',
    d.MO_TA='Báo cáo tổng hợp tình hình an toàn thông tin theo quý'
WHEN NOT MATCHED THEN INSERT (ID,MA_MAU,TEN_MAU,TAN_SUAT,IS_ACTIVE,DANH_SACH_MODULE,MO_TA,CREATED_AT,UPDATED_AT)
VALUES (8005,'ATTT','Báo cáo An toàn thông tin',2,1,'["GIAM_SAT_SOC","GIAM_SAT_NOC","ATTT_GIAI_PHAP","ATTT_HTTT_VAN_HANH","ATTT_HTTT_DAU_TU"]','Báo cáo tổng hợp tình hình an toàn thông tin theo quý',SYSTIMESTAMP,SYSTIMESTAMP);

MERGE INTO RPT_MAU_BAO_CAO d USING (SELECT 8006 ID FROM dual) s ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET
    d.MA_MAU='CAMERA', d.TEN_MAU='Báo cáo Hệ thống Camera', d.TAN_SUAT=3, d.IS_ACTIVE=1,
    d.DANH_SACH_MODULE='["CAMERA_QUAN_LY","CAMERA_THUC_TRANG"]',
    d.MO_TA='Báo cáo thực trạng hệ thống camera giám sát theo năm'
WHEN NOT MATCHED THEN INSERT (ID,MA_MAU,TEN_MAU,TAN_SUAT,IS_ACTIVE,DANH_SACH_MODULE,MO_TA,CREATED_AT,UPDATED_AT)
VALUES (8006,'CAMERA','Báo cáo Hệ thống Camera',3,1,'["CAMERA_QUAN_LY","CAMERA_THUC_TRANG"]','Báo cáo thực trạng hệ thống camera giám sát theo năm',SYSTIMESTAMP,SYSTIMESTAMP);

MERGE INTO RPT_MAU_BAO_CAO d USING (SELECT 8007 ID FROM dual) s ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET
    d.MA_MAU='VAN_BAN', d.TEN_MAU='Báo cáo Văn bản QPPL', d.TAN_SUAT=3, d.IS_ACTIVE=1,
    d.DANH_SACH_MODULE='["VAN_BAN_QPPL"]',
    d.MO_TA='Báo cáo rà soát văn bản quy phạm pháp luật về CNTT theo năm'
WHEN NOT MATCHED THEN INSERT (ID,MA_MAU,TEN_MAU,TAN_SUAT,IS_ACTIVE,DANH_SACH_MODULE,MO_TA,CREATED_AT,UPDATED_AT)
VALUES (8007,'VAN_BAN','Báo cáo Văn bản QPPL',3,1,'["VAN_BAN_QPPL"]','Báo cáo rà soát văn bản quy phạm pháp luật về CNTT theo năm',SYSTIMESTAMP,SYSTIMESTAMP);

-- ─── Cập nhật kỳ báo cáo mẫu: gắn MAU_BAO_CAO_ID + đổi KY_CODE sang format mới ─
-- 2026Q1 → dùng mẫu Nhân lực làm ví dụ minh họa
MERGE INTO RPT_KY_BAO_CAO d USING (SELECT 6001 ID FROM dual) s ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET
    d.KY_CODE='2026Q1_NHAN_LUC', d.NAM=2026, d.QUY=1, d.TRANG_THAI=2,
    d.MAU_BAO_CAO_ID=8001,
    d.NGAY_BAT_DAU=DATE '2026-01-01', d.NGAY_KET_THUC=DATE '2026-03-31',
    d.GHI_CHU='Kỳ Nhân lực Q1/2026 - đang mở (test flow snapshot)'
WHEN NOT MATCHED THEN INSERT (ID,KY_CODE,NAM,QUY,TRANG_THAI,MAU_BAO_CAO_ID,NGAY_BAT_DAU,NGAY_KET_THUC,GHI_CHU,CREATED_AT,UPDATED_AT)
VALUES (6001,'2026Q1_NHAN_LUC',2026,1,2,8001,DATE '2026-01-01',DATE '2026-03-31','Kỳ Nhân lực Q1/2026 - đang mở (test flow snapshot)',SYSTIMESTAMP,SYSTIMESTAMP);

-- 2025Q4 → dùng mẫu ATTT làm ví dụ thứ hai
MERGE INTO RPT_KY_BAO_CAO d USING (SELECT 6002 ID FROM dual) s ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET
    d.KY_CODE='2025Q4_ATTT', d.NAM=2025, d.QUY=4, d.TRANG_THAI=3,
    d.MAU_BAO_CAO_ID=8005,
    d.NGAY_BAT_DAU=DATE '2025-10-01', d.NGAY_KET_THUC=DATE '2025-12-31',
    d.GHI_CHU='Kỳ ATTT Q4/2025 - đã đóng'
WHEN NOT MATCHED THEN INSERT (ID,KY_CODE,NAM,QUY,TRANG_THAI,MAU_BAO_CAO_ID,NGAY_BAT_DAU,NGAY_KET_THUC,GHI_CHU,CREATED_AT,UPDATED_AT)
VALUES (6002,'2025Q4_ATTT',2025,4,3,8005,DATE '2025-10-01',DATE '2025-12-31','Kỳ ATTT Q4/2025 - đã đóng',SYSTIMESTAMP,SYSTIMESTAMP);

-- Thêm kỳ báo cáo năm để minh họa TAN_SUAT=3
MERGE INTO RPT_KY_BAO_CAO d USING (SELECT 6003 ID FROM dual) s ON (d.ID = s.ID)
WHEN MATCHED THEN UPDATE SET
    d.KY_CODE='2025_CAMERA', d.NAM=2025, d.QUY=NULL, d.TRANG_THAI=2,
    d.MAU_BAO_CAO_ID=8006,
    d.NGAY_BAT_DAU=DATE '2025-01-01', d.NGAY_KET_THUC=DATE '2025-12-31',
    d.GHI_CHU='Kỳ Camera năm 2025 - đang mở'
WHEN NOT MATCHED THEN INSERT (ID,KY_CODE,NAM,QUY,TRANG_THAI,MAU_BAO_CAO_ID,NGAY_BAT_DAU,NGAY_KET_THUC,GHI_CHU,CREATED_AT,UPDATED_AT)
VALUES (6003,'2025_CAMERA',2025,NULL,2,8006,DATE '2025-01-01',DATE '2025-12-31','Kỳ Camera năm 2025 - đang mở',SYSTIMESTAMP,SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'CAP_BAC_CONG_AN' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Cấp bậc công an', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('CAP_BAC_CONG_AN', 'Cấp bậc công an', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'THIEU_UY' VALUE, 'Thiếu úy' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'CAP_DON_VI' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Cấp đơn vị', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('CAP_DON_VI', 'Cấp đơn vị', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'BO' VALUE, 'Cấp Bộ (Bộ Công an)' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_DON_VI') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CUC' VALUE, 'Cấp Cục (đơn vị trực thuộc Bộ)' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_DON_VI') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'TINH' VALUE, 'Công an tỉnh/thành phố trực thuộc Trung ương' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_DON_VI') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'PHONG' VALUE, 'Cấp phòng và tương đương' NAME, 4 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_DON_VI') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'XA' VALUE, 'Công an cấp xã/phường/thị trấn' NAME, 5 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_DON_VI') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'HOC_VIEN' VALUE, 'Học viện/Trường/Bệnh viện CAND' NAME, 6 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_DON_VI') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'TRUNG_UY' VALUE, 'Trung úy' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'THUONG_UY' VALUE, 'Thượng úy' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DAI_UY' VALUE, 'Đại úy' NAME, 4 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'THIEU_TA' VALUE, 'Thiếu tá' NAME, 5 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'TRUNG_TA' VALUE, 'Trung tá' NAME, 6 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'THUONG_TA' VALUE, 'Thượng tá' NAME, 7 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DAI_TA' VALUE, 'Đại tá' NAME, 8 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'THIEU_TUONG' VALUE, 'Thiếu tướng' NAME, 9 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'TRUNG_TUONG' VALUE, 'Trung tướng' NAME, 10 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'THUONG_TUONG' VALUE, 'Thượng tướng' NAME, 11 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DAI_TUONG' VALUE, 'Đại tướng' NAME, 12 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'LOAI_MANG_GIAM_SAT' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Loại mạng giám sát', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('LOAI_MANG_GIAM_SAT', 'Loại mạng giám sát', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'MANG_NOI_BO' VALUE, 'Mạng nội bộ' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOAI_MANG_GIAM_SAT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'MANG_DIEN_RONG' VALUE, 'Mạng diện rộng' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOAI_MANG_GIAM_SAT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'MANG_TRUYEN_SO_LIEU_CHUYEN_DUNG' VALUE, 'Mạng truyền số liệu chuyên dùng' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOAI_MANG_GIAM_SAT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'INTERNET' VALUE, 'Internet' NAME, 4 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOAI_MANG_GIAM_SAT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'NHOM_CAMERA' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Nhom camera', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('NHOM_CAMERA', 'Nhom camera', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NHOM_1' VALUE, 'Nhom 1' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'NHOM_CAMERA') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NHOM_2' VALUE, 'Nhom 2' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'NHOM_CAMERA') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NHOM_3' VALUE, 'Nhom 3' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'NHOM_CAMERA') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'DUONG_TRUYEN_CAMERA' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Duong truyen camera', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('DUONG_TRUYEN_CAMERA', 'Duong truyen camera', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'MPLS' VALUE, 'MPLS' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'DUONG_TRUYEN_CAMERA') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'SDWAN' VALUE, 'SD-WAN' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'DUONG_TRUYEN_CAMERA') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'INTERNET' VALUE, 'Internet' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'DUONG_TRUYEN_CAMERA') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'LOP_GIAM_SAT' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Lớp giám sát', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('LOP_GIAM_SAT', 'Lớp giám sát', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'LOP_MANG' VALUE, 'Lớp mạng' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOP_GIAM_SAT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'LOP_UNG_DUNG' VALUE, 'Lớp ứng dụng' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOP_GIAM_SAT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'LOP_DU_LIEU' VALUE, 'Lớp dữ liệu' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOP_GIAM_SAT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'LOP_THIET_BI' VALUE, 'Lớp thiết bị' NAME, 4 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOP_GIAM_SAT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'THUC_TRANG_GIAM_SAT' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Thực trạng giám sát', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('THUC_TRANG_GIAM_SAT', 'Thực trạng giám sát', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CHUA_TRIEN_KHAI' VALUE, 'Chưa triển khai' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'THUC_TRANG_GIAM_SAT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DA_TRIEN_KHAI' VALUE, 'Đã triển khai' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'THUC_TRANG_GIAM_SAT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'THUE_DICH_VU' VALUE, 'Thuê dịch vụ' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'THUC_TRANG_GIAM_SAT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'TINH_TRANG_PHE_DUYET_ATTT' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Tình trạng phê duyệt hồ sơ ATTT', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('TINH_TRANG_PHE_DUYET_ATTT', 'Tình trạng phê duyệt hồ sơ ATTT', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DA_PHE_DUYET' VALUE, 'Đã phê duyệt' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'TINH_TRANG_PHE_DUYET_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DANG_XAY_DUNG_HO_SO' VALUE, 'Đang xây dựng hồ sơ' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'TINH_TRANG_PHE_DUYET_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CHUA_PHE_DUYET' VALUE, 'Chưa phê duyệt (có hồ sơ)' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'TINH_TRANG_PHE_DUYET_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CHUA_XAY_DUNG_HO_SO' VALUE, 'Chưa xây dựng hồ sơ' NAME, 4 SORT_ORDER FROM CODES c WHERE c.CODE = 'TINH_TRANG_PHE_DUYET_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'GIAI_PHAP_ATTT' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Giải pháp an toàn thông tin', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('GIAI_PHAP_ATTT', 'Giải pháp an toàn thông tin', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'ANTIVIRUS' VALUE, 'Phần mềm Antivirus' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'GIAI_PHAP_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'EDR' VALUE, 'Phần mềm EDR (Endpoint Detection & Response)' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'GIAI_PHAP_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'FIREWALL' VALUE, 'Tường lửa (Firewall)' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'GIAI_PHAP_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'IDS_IPS' VALUE, 'Hệ thống IDS/IPS' NAME, 4 SORT_ORDER FROM CODES c WHERE c.CODE = 'GIAI_PHAP_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'SIEM' VALUE, 'Hệ thống SIEM' NAME, 5 SORT_ORDER FROM CODES c WHERE c.CODE = 'GIAI_PHAP_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'WAF' VALUE, 'Tường lửa ứng dụng Web (WAF)' NAME, 6 SORT_ORDER FROM CODES c WHERE c.CODE = 'GIAI_PHAP_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'VPN' VALUE, 'Mạng riêng ảo (VPN)' NAME, 7 SORT_ORDER FROM CODES c WHERE c.CODE = 'GIAI_PHAP_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DLP' VALUE, 'Ngăn ngừa rò rỉ dữ liệu (DLP)' NAME, 8 SORT_ORDER FROM CODES c WHERE c.CODE = 'GIAI_PHAP_ATTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CHUYEN_VIEN' VALUE, 'Chuyên viên (dân sự)' NAME, 13 SORT_ORDER FROM CODES c WHERE c.CODE = 'CAP_BAC_CONG_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'NGUON_VON_DU_AN' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Nguồn vốn dự án đầu tư CNTT', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('NGUON_VON_DU_AN', 'Nguồn vốn dự án đầu tư CNTT', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NGAN_SACH_NHA_NUOC' VALUE, 'Ngân sách nhà nước' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'NGUON_VON_DU_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'BO_CONG_AN' VALUE, 'Ngân sách Bộ Công an' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'NGUON_VON_DU_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DIA_PHUONG' VALUE, 'Ngân sách địa phương' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'NGUON_VON_DU_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'KHAC' VALUE, 'Nguồn khác' NAME, 4 SORT_ORDER FROM CODES c WHERE c.CODE = 'NGUON_VON_DU_AN') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'TRINH_DO_CNTT' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Trình độ CNTT', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('TRINH_DO_CNTT', 'Trình độ CNTT', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'TIEN_SI' VALUE, 'Tiến sĩ' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'TRINH_DO_CNTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'THAC_SI' VALUE, 'Thạc sĩ' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'TRINH_DO_CNTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DAI_HOC' VALUE, 'Đại học' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'TRINH_DO_CNTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CAO_DANG' VALUE, 'Cao đẳng' NAME, 4 SORT_ORDER FROM CODES c WHERE c.CODE = 'TRINH_DO_CNTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'TRUNG_CAP' VALUE, 'Trung cấp' NAME, 5 SORT_ORDER FROM CODES c WHERE c.CODE = 'TRINH_DO_CNTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'SO_CAP' VALUE, 'Sơ cấp' NAME, 6 SORT_ORDER FROM CODES c WHERE c.CODE = 'TRINH_DO_CNTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CHUA_QUA_DAO_TAO' VALUE, 'Chưa qua đào tạo' NAME, 7 SORT_ORDER FROM CODES c WHERE c.CODE = 'TRINH_DO_CNTT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'TRINH_DO_LLCT' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Trình độ lý luận chính trị', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('TRINH_DO_LLCT', 'Trình độ lý luận chính trị', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CAO_CAP' VALUE, 'Cao cấp' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'TRINH_DO_LLCT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'TRUNG_CAP' VALUE, 'Trung cấp' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'TRINH_DO_LLCT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'SO_CAP' VALUE, 'Sơ cấp' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'TRINH_DO_LLCT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CHUA_QUA_DAO_TAO' VALUE, 'Chưa qua đào tạo' NAME, 4 SORT_ORDER FROM CODES c WHERE c.CODE = 'TRINH_DO_LLCT') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'LOAI_NHAN_LUC' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Loại nhân lực', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('LOAI_NHAN_LUC', 'Loại nhân lực', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CHUYEN_TRACH' VALUE, 'Chuyên trách' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOAI_NHAN_LUC') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'KIEM_NHIEM' VALUE, 'Kiêm nhiệm' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOAI_NHAN_LUC') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'GIOI_TINH' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Giới tính', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('GIOI_TINH', 'Giới tính', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NAM' VALUE, 'Nam' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'GIOI_TINH') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NU' VALUE, 'Nữ' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'GIOI_TINH') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'NOI_DUNG_DAO_TAO_HV' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Nội dung đào tạo học viên', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('NOI_DUNG_DAO_TAO_HV', 'Nội dung đào tạo học viên', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'LOAI_DV_THONG_KE_MANG' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Loại đơn vị thống kê hạ tầng mạng', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('LOAI_DV_THONG_KE_MANG', 'Loại đơn vị thống kê hạ tầng mạng', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CAP_PHONG_BO' VALUE, 'Công an cấp phòng và tương đương thuộc các đơn vị trực thuộc Bộ' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOAI_DV_THONG_KE_MANG') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CAP_PHONG_TINH' VALUE, 'Công an cấp phòng; Công an cấp xã, phường và tương đương thuộc Công an tỉnh/thành phố' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOAI_DV_THONG_KE_MANG') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'LOAI_PHAN_MEM_CSDL' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Loại phần mềm/CSDL', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('LOAI_PHAN_MEM_CSDL', 'Loại phần mềm/CSDL', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DUNG_CHUNG' VALUE, 'Do Cuc nghiep vu trien khai dung chung' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOAI_PHAN_MEM_CSDL') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'TU_PHAT_TRIEN' VALUE, 'Do don vi dia phuong tu nghien cuu phat trien' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'LOAI_PHAN_MEM_CSDL') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'HTTT_TIEU_CHUAN_CAND' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Hệ thống thông tin tiêu chuẩn CAND', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('HTTT_TIEU_CHUAN_CAND', 'Hệ thống thông tin tiêu chuẩn CAND', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'QLVB_DIEU_HANH' VALUE, 'He thong quan ly van ban va dieu hanh trong CAND' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'HTTT_TIEU_CHUAN_CAND') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CHUYEN_NGANH_CNTT' VALUE, 'Chuyên ngành công nghệ thông tin' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'NOI_DUNG_DAO_TAO_HV') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NGANH_GAN_CNTT' VALUE, 'Ngành gần công nghệ thông tin' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'NOI_DUNG_DAO_TAO_HV') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'NHOM_NANG_LUC_SO' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Nhóm vị trí năng lực số', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('NHOM_NANG_LUC_SO', 'Nhóm vị trí năng lực số', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NHOM_1' VALUE, 'Nhóm 1 - Không yêu cầu kỹ năng sâu về công nghệ số' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'NHOM_NANG_LUC_SO') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NHOM_2' VALUE, 'Nhóm 2 - Vận hành, hỗ trợ kỹ thuật hệ thống CNTT, viễn thông cấp cơ sở' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'NHOM_NANG_LUC_SO') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NHOM_3' VALUE, 'Nhóm 3 - Công tác CNTT, quản lý CSDL, giảng dạy không yêu cầu cao về công nghệ số' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'NHOM_NANG_LUC_SO') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NHOM_4' VALUE, 'Nhóm 4 - Nghiệp vụ quản lý hành chính, hồ sơ, xử lý thông tin gắn với HTTT và CSDL chuyên ngành' NAME, 4 SORT_ORDER FROM CODES c WHERE c.CODE = 'NHOM_NANG_LUC_SO') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NHOM_5' VALUE, 'Nhóm 5 - Trinh sát kỹ thuật, giám sát, thu thập, phân tích, phục hồi dữ liệu và chứng cứ điện tử' NAME, 5 SORT_ORDER FROM CODES c WHERE c.CODE = 'NHOM_NANG_LUC_SO') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NHOM_6' VALUE, 'Nhóm 6 - Bảo vệ an ninh không gian mạng, phòng chống tội phạm công nghệ cao và xâm phạm ANQG' NAME, 6 SORT_ORDER FROM CODES c WHERE c.CODE = 'NHOM_NANG_LUC_SO') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NHOM_7' VALUE, 'Nhóm 7 - Quản lý, vận hành, bảo đảm ATTT hệ thống CNTT, hạ tầng kỹ thuật, viễn thông, mật mã CAND' NAME, 7 SORT_ORDER FROM CODES c WHERE c.CODE = 'NHOM_NANG_LUC_SO') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'NHOM_8' VALUE, 'Nhóm 8 - Nghiên cứu khoa học, phát triển công nghệ, giảng dạy về công nghệ số, an ninh mạng, mật mã CAND' NAME, 8 SORT_ORDER FROM CODES c WHERE c.CODE = 'NHOM_NANG_LUC_SO') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODES d USING (SELECT 'TINH_TRANG_TRIEN_KHAI_VB' CODE FROM dual) s ON (d.CODE = s.CODE)
WHEN MATCHED THEN UPDATE SET d.NAME = 'Tình trạng triển khai văn bản QPPL', d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE, NAME, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES ('TINH_TRANG_TRIEN_KHAI_VB', 'Tình trạng triển khai văn bản QPPL', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'CHUA_TRIEN_KHAI' VALUE, 'Chưa triển khai' NAME, 1 SORT_ORDER FROM CODES c WHERE c.CODE = 'TINH_TRANG_TRIEN_KHAI_VB') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DANG_TRIEN_KHAI' VALUE, 'Đang triển khai' NAME, 2 SORT_ORDER FROM CODES c WHERE c.CODE = 'TINH_TRANG_TRIEN_KHAI_VB') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

MERGE INTO CODE_VALUES d USING (SELECT c.ID CODE_ID, 'DA_TRIEN_KHAI' VALUE, 'Đã triển khai' NAME, 3 SORT_ORDER FROM CODES c WHERE c.CODE = 'TINH_TRANG_TRIEN_KHAI_VB') s ON (d.CODE_ID = s.CODE_ID AND d.VALUE = s.VALUE)
WHEN MATCHED THEN UPDATE SET d.NAME = s.NAME, d.SORT_ORDER = s.SORT_ORDER, d.IS_ACTIVE = 1, d.IS_SYSTEM = 1, d.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (CODE_ID, VALUE, NAME, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT)
VALUES (s.CODE_ID, s.VALUE, s.NAME, s.SORT_ORDER, 1, 1, SYSTIMESTAMP, SYSTIMESTAMP);

-- Password hashes are intentionally not seeded in SQL because BCrypt output is environment-independent but frequently rotated.
-- Use runtime BaselineDataSeeder for USERS/ROLES/PERMISSIONS population in lower environments and integration tests.
