-- V13: Thêm bảng RPT_MAU_BAO_CAO (Report Template) và mở rộng RPT_KY_BAO_CAO
--
-- Vấn đề: V1-V12 coi KyBaoCao là "kỳ theo quý" dùng chung cho tất cả module.
-- Thực tế: Hệ thống có nhiều mẫu báo cáo độc lập (nhân lực, ATTT, camera...),
--          mỗi mẫu có tần suất riêng (tháng/quý/năm) và nhóm module riêng.
--          Một KyBaoCao phải gắn với đúng 1 mẫu báo cáo cụ thể.
--
-- Thay đổi:
--   1. Tạo RPT_MAU_BAO_CAO  — định nghĩa loại báo cáo
--   2. Mở rộng RPT_KY_BAO_CAO — thêm MAU_BAO_CAO_ID + THANG + mở rộng KY_CODE
--   3. KY_CODE đổi format: "2025Q1_NHAN_LUC" thay vì "2025Q1"

-- ─── 1. Bảng mẫu báo cáo ─────────────────────────────────────────────────────
CREATE TABLE RPT_MAU_BAO_CAO (
    ID                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MA_MAU              NVARCHAR2(50)  NOT NULL,   -- e.g. "NHAN_LUC", "ATTT", "CAMERA"
    TEN_MAU             NVARCHAR2(200) NOT NULL,   -- e.g. "Báo cáo Nhân lực CNTT"
    KY_CODE_PREFIX      NVARCHAR2(30)  NOT NULL,   -- e.g. "NHAN_LUC" -> KyCode = "2025Q1_NHAN_LUC"
    MO_TA               NVARCHAR2(1000) NULL,
    -- Tần suất: 1=Tháng, 2=Quý, 3=Năm
    TAN_SUAT            NUMBER(1) DEFAULT 2 NOT NULL,
    -- JSON array các module key, e.g. ["NHAN_LUC_CNTT","NANG_LUC_SO"]
    -- Dùng để: (a) frontend biết màn nào cần điền, (b) snapshot biết gom bảng nào
    DANH_SACH_MODULE    NCLOB NOT NULL,
    IS_ACTIVE           NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT_UTC      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT_UTC      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY          NUMBER(19) NULL,
    UPDATED_BY          NUMBER(19) NULL
);

CREATE UNIQUE INDEX UX_RPT_MAU_BAO_CAO_MA ON RPT_MAU_BAO_CAO (MA_MAU);

-- ─── 2. Mở rộng RPT_KY_BAO_CAO ───────────────────────────────────────────────

-- 2a. Mở rộng KY_CODE: "2025Q1" (10 chars) → "2025Q1_NHAN_LUC" (15 chars max ~50)
ALTER TABLE RPT_KY_BAO_CAO MODIFY (KY_CODE NVARCHAR2(50));

-- 2b. Thêm cột THANG cho báo cáo tháng (NULL nếu báo cáo theo quý/năm)
ALTER TABLE RPT_KY_BAO_CAO ADD (THANG NUMBER(2) NULL);

-- 2c. Thêm FK đến mẫu báo cáo (NULL để backward-compat với dữ liệu cũ)
ALTER TABLE RPT_KY_BAO_CAO ADD (MAU_BAO_CAO_ID NUMBER(19) NULL);

ALTER TABLE RPT_KY_BAO_CAO ADD CONSTRAINT FK_RPT_KY_MAU
    FOREIGN KEY (MAU_BAO_CAO_ID) REFERENCES RPT_MAU_BAO_CAO(ID);

CREATE INDEX IX_RPT_KY_BAO_CAO_MAU ON RPT_KY_BAO_CAO (MAU_BAO_CAO_ID);

-- ─── 3. Comment mô tả ràng buộc logic (enforce ở application layer) ───────────
-- TAN_SUAT=1 (Tháng) → THANG NOT NULL, QUY NULL
-- TAN_SUAT=2 (Quý)   → QUY NOT NULL, THANG NULL
-- TAN_SUAT=3 (Năm)   → QUY NULL, THANG NULL
-- KY_CODE convention: {NAM}T{MM}_{PREFIX} | {NAM}Q{Q}_{PREFIX} | {NAM}_{PREFIX}
--   Ví dụ: "2025T06_ATTT", "2025Q1_NHAN_LUC", "2025_CAMERA"
