-- Nhom A: Xoa KY_BAO_CAO_CODE vi day la du lieu hien tai, khong phu thuoc ky.

CREATE OR REPLACE PROCEDURE DROP_BIZ_KY_CODE_IF_EXISTS(
	p_table_name IN VARCHAR2,
	p_index_name IN VARCHAR2
) AS
	v_index_count NUMBER := 0;
	v_column_count NUMBER := 0;
BEGIN
	SELECT COUNT(1)
	  INTO v_index_count
	  FROM USER_INDEXES
	 WHERE INDEX_NAME = UPPER(p_index_name);

	IF v_index_count > 0 THEN
		EXECUTE IMMEDIATE 'DROP INDEX ' || p_index_name;
	END IF;

	SELECT COUNT(1)
	  INTO v_column_count
	  FROM USER_TAB_COLS
	 WHERE TABLE_NAME = UPPER(p_table_name)
	   AND COLUMN_NAME = 'KY_BAO_CAO_CODE';

	IF v_column_count > 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name || ' DROP COLUMN KY_BAO_CAO_CODE';
	END IF;
END;
/

BEGIN
	DROP_BIZ_KY_CODE_IF_EXISTS('BIZ_NHAN_LUC_CNTT', 'IX_BIZ_NHAN_LUC_CNTT_DV_KY');
	DROP_BIZ_KY_CODE_IF_EXISTS('BIZ_HE_THONG_THONG_TIN', 'IX_BIZ_HE_THONG_THONG_TIN_DV_KY');
	DROP_BIZ_KY_CODE_IF_EXISTS('BIZ_THIET_BI_CNTT', 'IX_BIZ_TBCNTT_DV_KY');
	DROP_BIZ_KY_CODE_IF_EXISTS('BIZ_HA_TANG_MANG', 'IX_BIZ_HTM_DV_KY');
	DROP_BIZ_KY_CODE_IF_EXISTS('BIZ_GIAM_SAT_SOC', 'IX_BIZ_GSS_DV_KY');
	DROP_BIZ_KY_CODE_IF_EXISTS('BIZ_GIAM_SAT_NOC', 'IX_BIZ_GSN_DV_KY');
	DROP_BIZ_KY_CODE_IF_EXISTS('BIZ_GIAI_PHAP_ATTT', 'IX_BIZ_GPATTT_DV_KY');
	DROP_BIZ_KY_CODE_IF_EXISTS('BIZ_CAMERA_QUAN_LY', 'IX_BIZ_CQL_DV_KY');
	DROP_BIZ_KY_CODE_IF_EXISTS('BIZ_CAMERA_THUC_TRANG', 'IX_BIZ_CTT_DV_KY');
END;
/

DROP PROCEDURE DROP_BIZ_KY_CODE_IF_EXISTS;
/