-- V21: cap nhat cac module dao tao theo form thuc te

BEGIN
    DECLARE
        v_count NUMBER := 0;
    BEGIN
        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_BOI_DUONG'
           AND COLUMN_NAME = 'KINH_PHI';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG DROP COLUMN KINH_PHI';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_BOI_DUONG'
           AND COLUMN_NAME = 'NGUON_KINH_PHI';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG DROP COLUMN NGUON_KINH_PHI';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_BOI_DUONG'
           AND COLUMN_NAME = 'KET_QUA';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG DROP COLUMN KET_QUA';
        END IF;
    END;
END;
/

DELETE FROM BIZ_DAO_TAO_HOC_VIEN;
/

BEGIN
    DECLARE
        v_count NUMBER := 0;
    BEGIN
        SELECT COUNT(1) INTO v_count
          FROM USER_INDEXES
         WHERE INDEX_NAME = 'UX_BIZ_DTHV_DV_KY_ND';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'DROP INDEX UX_BIZ_DTHV_DV_KY_ND';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_INDEXES
         WHERE INDEX_NAME = 'IX_BIZ_DTHV_DV_KY';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_DTHV_DV_KY';
        END IF;
    END;
END;
/

BEGIN
    DECLARE
        v_count NUMBER := 0;
    BEGIN
        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'TEN_TRUONG';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN TEN_TRUONG';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'TEN_KHOA_HOC';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN TEN_KHOA_HOC';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'TRINH_DO';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN TRINH_DO';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'SO_LUONG_TUYEN';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN SO_LUONG_TUYEN';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'SO_LUONG_TOT_NGHIEP';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN SO_LUONG_TOT_NGHIEP';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'NAM_HOC';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN NAM_HOC';
        END IF;
    END;
END;
/

BEGIN
    DECLARE
        v_count NUMBER := 0;
    BEGIN
        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'NOI_DUNG_DAO_TAO';
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN ADD (NOI_DUNG_DAO_TAO NVARCHAR2(50) DEFAULT ''CHUYEN_NGANH_CNTT'' NOT NULL)';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'SO_TIEN_SI';
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN ADD (SO_TIEN_SI NUMBER(10) DEFAULT 0 NOT NULL)';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'SO_THAC_SI';
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN ADD (SO_THAC_SI NUMBER(10) DEFAULT 0 NOT NULL)';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'SO_DAI_HOC';
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN ADD (SO_DAI_HOC NUMBER(10) DEFAULT 0 NOT NULL)';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'SO_CAO_DANG';
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN ADD (SO_CAO_DANG NUMBER(10) DEFAULT 0 NOT NULL)';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
           AND COLUMN_NAME = 'SO_TRUNG_CAP';
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN ADD (SO_TRUNG_CAP NUMBER(10) DEFAULT 0 NOT NULL)';
        END IF;
    END;
END;
/

CREATE INDEX IX_BIZ_DTHV_DV_KY ON BIZ_DAO_TAO_HOC_VIEN (DON_VI_ID, KY_BAO_CAO_CODE);
/
CREATE UNIQUE INDEX UX_BIZ_DTHV_DV_KY_ND ON BIZ_DAO_TAO_HOC_VIEN (DON_VI_ID, KY_BAO_CAO_CODE, NOI_DUNG_DAO_TAO);
/