-- V22: redesign BIZ_NANG_LUC_SO theo form thuc te

DELETE FROM BIZ_NANG_LUC_SO;
/

BEGIN
    DECLARE
        v_count NUMBER := 0;
    BEGIN
        SELECT COUNT(1) INTO v_count
          FROM USER_INDEXES
         WHERE INDEX_NAME = 'UX_BIZ_NLS_DV_KY_NHOM';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'DROP INDEX UX_BIZ_NLS_DV_KY_NHOM';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_INDEXES
         WHERE INDEX_NAME = 'IX_BIZ_NLS_DV_KY';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_NLS_DV_KY';
        END IF;
    END;
END;
/

BEGIN
    DECLARE
        v_count NUMBER := 0;
    BEGIN
        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_NANG_LUC_SO'
           AND COLUMN_NAME = 'TONG_CBCS';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO DROP COLUMN TONG_CBCS';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_NANG_LUC_SO'
           AND COLUMN_NAME = 'SO_CO_MAY_TINH';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO DROP COLUMN SO_CO_MAY_TINH';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_NANG_LUC_SO'
           AND COLUMN_NAME = 'SO_SU_DUNG_PHAN_MEM';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO DROP COLUMN SO_SU_DUNG_PHAN_MEM';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_NANG_LUC_SO'
           AND COLUMN_NAME = 'SO_DA_TAP_HUAN';
        IF v_count > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO DROP COLUMN SO_DA_TAP_HUAN';
        END IF;
    END;
END;
/

BEGIN
    DECLARE
        v_count NUMBER := 0;
    BEGIN
        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_NANG_LUC_SO'
           AND COLUMN_NAME = 'NHOM_VI_TRI';
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO ADD (NHOM_VI_TRI NVARCHAR2(20) DEFAULT ''NHOM_1'' NOT NULL)';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_NANG_LUC_SO'
           AND COLUMN_NAME = 'TONG_SO_DIEN_DANH_GIA';
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO ADD (TONG_SO_DIEN_DANH_GIA NUMBER(10) DEFAULT 0 NOT NULL)';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_NANG_LUC_SO'
           AND COLUMN_NAME = 'TONG_SO_DAT';
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO ADD (TONG_SO_DAT NUMBER(10) DEFAULT 0 NOT NULL)';
        END IF;

        SELECT COUNT(1) INTO v_count
          FROM USER_TAB_COLS
         WHERE TABLE_NAME = 'BIZ_NANG_LUC_SO'
           AND COLUMN_NAME = 'TONG_SO_CHUA_DAT';
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO ADD (TONG_SO_CHUA_DAT NUMBER(10) DEFAULT 0 NOT NULL)';
        END IF;
    END;
END;
/

CREATE INDEX IX_BIZ_NLS_DV_KY ON BIZ_NANG_LUC_SO (DON_VI_ID, KY_BAO_CAO_CODE);
/
CREATE UNIQUE INDEX UX_BIZ_NLS_DV_KY_NHOM ON BIZ_NANG_LUC_SO (DON_VI_ID, KY_BAO_CAO_CODE, NHOM_VI_TRI);
/