-- V25: Rename DM_LOAI_THIET_BI -> REF_LOAI_THIET_BI

DECLARE
	v_dm_count NUMBER;
	v_ref_count NUMBER;
BEGIN
	SELECT COUNT(*) INTO v_dm_count FROM USER_TABLES WHERE TABLE_NAME = 'DM_LOAI_THIET_BI';
	SELECT COUNT(*) INTO v_ref_count FROM USER_TABLES WHERE TABLE_NAME = 'REF_LOAI_THIET_BI';

	IF v_dm_count > 0 AND v_ref_count = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE DM_LOAI_THIET_BI RENAME TO REF_LOAI_THIET_BI';
	END IF;
END;
/