ALTER TABLE BIZ_VAN_BAN_QPPL MODIFY (TEN_VAN_BAN NVARCHAR2(500) NULL);
ALTER TABLE BIZ_VAN_BAN_QPPL MODIFY (LOAI_VAN_BAN NVARCHAR2(100) NULL);
ALTER TABLE BIZ_VAN_BAN_QPPL MODIFY (CO_QUAN_BAN_HANH NVARCHAR2(200) NULL);

ALTER TABLE BIZ_VAN_BAN_QPPL RENAME COLUMN TOM_TAT TO TRICH_YEU;

ALTER TABLE BIZ_VAN_BAN_QPPL ADD (
    TINH_TRANG_TRIEN_KHAI NVARCHAR2(50) NULL
);