ALTER TABLE REF_DON_VI ADD (
    CAP_DON_VI NVARCHAR2(20) NULL,
    WEBSITE_NOI_BO NVARCHAR2(200) NULL,
    WEBSITE_INTERNET NVARCHAR2(200) NULL,
    TONG_BIEN_CHE NUMBER(10) NULL
);

CREATE INDEX IX_REF_DV_CAP ON REF_DON_VI (CAP_DON_VI);