ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN CAP_DO_ATTT;
ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN CO_KIEM_TRA;
ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN NGAY_KIEM_TRA;
ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN DON_VI_KIEM_TRA;
ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN KET_QUA;
ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN LO_HONG_PHAT_HIEN;
ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN LO_HONG_XU_LY;

ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH ADD (
    CHU_QUAN NVARCHAR2(200) NULL,
    DON_VI_VAN_HANH NVARCHAR2(200) NULL,
    CAP_DO_DE_XUAT NVARCHAR2(20) NULL,
    TINH_TRANG_PHE_DUYET NVARCHAR2(50) NULL,
    QUYET_DINH_PHE_DUYET NVARCHAR2(200) NULL,
    QUY_CHE_ATTT NVARCHAR2(200) NULL,
    DU_KIEN_NGAY_PHE_DUYET DATE NULL,
    DA_TRIEN_KHAI_PHUONG_AN NUMBER(1) DEFAULT 0 NOT NULL,
    DU_KIEN_NGAY_TRIEN_KHAI DATE NULL,
    KIEM_TRA_DANH_GIA NVARCHAR2(500) NULL
);

ALTER TABLE BIZ_ATTT_HTTT_DAU_TU DROP COLUMN HANG_MUC;
ALTER TABLE BIZ_ATTT_HTTT_DAU_TU DROP COLUMN KINH_PHI;
ALTER TABLE BIZ_ATTT_HTTT_DAU_TU DROP COLUMN NGUON_KINH_PHI;
ALTER TABLE BIZ_ATTT_HTTT_DAU_TU DROP COLUMN TRANG_THAI;

ALTER TABLE BIZ_ATTT_HTTT_DAU_TU ADD (
    CHU_QUAN NVARCHAR2(200) NULL,
    DON_VI_VAN_HANH NVARCHAR2(200) NULL,
    CAP_DO_DE_XUAT NVARCHAR2(20) NULL,
    NGAY_PHE_DUYET_HSDXCD DATE NULL,
    QUYET_DINH_PHE_DUYET NVARCHAR2(200) NULL,
    DA_LONG_GHEP_THUYET_MINH NUMBER(1) DEFAULT 0 NOT NULL
);

TRUNCATE TABLE BIZ_GIAI_PHAP_ATTT;
ALTER TABLE BIZ_GIAI_PHAP_ATTT DROP COLUMN LOAI_GIAI_PHAP;
ALTER TABLE BIZ_GIAI_PHAP_ATTT DROP COLUMN TEN_SAN_PHAM;
ALTER TABLE BIZ_GIAI_PHAP_ATTT DROP COLUMN NHA_CUNG_CAP;
ALTER TABLE BIZ_GIAI_PHAP_ATTT DROP COLUMN SO_LUONG;
ALTER TABLE BIZ_GIAI_PHAP_ATTT DROP COLUMN NAM_DUA_VAO;

ALTER TABLE BIZ_GIAI_PHAP_ATTT ADD (
    TEN_GIAI_PHAP NVARCHAR2(50) NOT NULL,
    MAY_TINH_BCANET_SL NUMBER(10) DEFAULT 0 NOT NULL,
    MAY_TINH_BCANET_TS NUMBER(10) DEFAULT 0 NOT NULL,
    MAY_TINH_INTERNET_SL NUMBER(10) DEFAULT 0 NOT NULL,
    MAY_TINH_INTERNET_TS NUMBER(10) DEFAULT 0 NOT NULL,
    MAY_TINH_LOCAL_SL NUMBER(10) DEFAULT 0 NOT NULL,
    MAY_TINH_LOCAL_TS NUMBER(10) DEFAULT 0 NOT NULL,
    MAY_CHU_BCANET_SL NUMBER(10) DEFAULT 0 NOT NULL,
    MAY_CHU_BCANET_TS NUMBER(10) DEFAULT 0 NOT NULL,
    MAY_CHU_INTERNET_SL NUMBER(10) DEFAULT 0 NOT NULL,
    MAY_CHU_INTERNET_TS NUMBER(10) DEFAULT 0 NOT NULL,
    MAY_CHU_LOCAL_SL NUMBER(10) DEFAULT 0 NOT NULL,
    MAY_CHU_LOCAL_TS NUMBER(10) DEFAULT 0 NOT NULL
);

ALTER TABLE BIZ_GIAI_PHAP_ATTT ADD CONSTRAINT UQ_GPATTT_DV_GP UNIQUE (DON_VI_ID, TEN_GIAI_PHAP);

BEGIN
    FOR idx IN (
        SELECT INDEX_NAME
        FROM USER_INDEXES
        WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT'
          AND INDEX_NAME = 'IX_BIZ_GPATTT_DV'
    ) LOOP
        EXECUTE IMMEDIATE 'DROP INDEX ' || idx.INDEX_NAME;
    END LOOP;
END;
/

CREATE INDEX IX_BIZ_GPATTT_DV ON BIZ_GIAI_PHAP_ATTT (DON_VI_ID);