-- Rename GIAI_PHAP_ATTT matrix columns from TU/MAU to SL/TS for already-migrated databases.
BEGIN
    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_TINH_BCANET_TU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_TINH_BCANET_TU TO MAY_TINH_BCANET_SL';
    END LOOP;

    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_TINH_BCANET_MAU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_TINH_BCANET_MAU TO MAY_TINH_BCANET_TS';
    END LOOP;

    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_TINH_INTERNET_TU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_TINH_INTERNET_TU TO MAY_TINH_INTERNET_SL';
    END LOOP;

    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_TINH_INTERNET_MAU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_TINH_INTERNET_MAU TO MAY_TINH_INTERNET_TS';
    END LOOP;

    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_TINH_LOCAL_TU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_TINH_LOCAL_TU TO MAY_TINH_LOCAL_SL';
    END LOOP;

    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_TINH_LOCAL_MAU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_TINH_LOCAL_MAU TO MAY_TINH_LOCAL_TS';
    END LOOP;

    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_CHU_BCANET_TU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_CHU_BCANET_TU TO MAY_CHU_BCANET_SL';
    END LOOP;

    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_CHU_BCANET_MAU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_CHU_BCANET_MAU TO MAY_CHU_BCANET_TS';
    END LOOP;

    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_CHU_INTERNET_TU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_CHU_INTERNET_TU TO MAY_CHU_INTERNET_SL';
    END LOOP;

    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_CHU_INTERNET_MAU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_CHU_INTERNET_MAU TO MAY_CHU_INTERNET_TS';
    END LOOP;

    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_CHU_LOCAL_TU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_CHU_LOCAL_TU TO MAY_CHU_LOCAL_SL';
    END LOOP;

    FOR c IN (SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT' AND COLUMN_NAME = 'MAY_CHU_LOCAL_MAU') LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAI_PHAP_ATTT RENAME COLUMN MAY_CHU_LOCAL_MAU TO MAY_CHU_LOCAL_TS';
    END LOOP;
END;
/