-- Rename ATTT solution table to ATTT-prefixed naming convention.
-- BIZ_GIAI_PHAP_ATTT -> BIZ_ATTT_GIAI_PHAP
DECLARE
    v_index_count NUMBER := 0;
BEGIN
    FOR t IN (
        SELECT TABLE_NAME
        FROM USER_TABLES
        WHERE TABLE_NAME = 'BIZ_GIAI_PHAP_ATTT'
    ) LOOP
        EXECUTE IMMEDIATE 'RENAME BIZ_GIAI_PHAP_ATTT TO BIZ_ATTT_GIAI_PHAP';
    END LOOP;

    FOR i IN (
        SELECT INDEX_NAME
        FROM USER_INDEXES
        WHERE TABLE_NAME = 'BIZ_ATTT_GIAI_PHAP'
          AND INDEX_NAME = 'IX_BIZ_GPATTT_DV'
    ) LOOP
        EXECUTE IMMEDIATE 'ALTER INDEX IX_BIZ_GPATTT_DV RENAME TO IX_BIZ_ATTT_GIAI_PHAP_DV';
    END LOOP;

    SELECT COUNT(1)
    INTO v_index_count
    FROM USER_INDEXES
    WHERE TABLE_NAME = 'BIZ_ATTT_GIAI_PHAP'
      AND INDEX_NAME = 'IX_BIZ_ATTT_GIAI_PHAP_DV';

    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_BIZ_ATTT_GIAI_PHAP_DV ON BIZ_ATTT_GIAI_PHAP (DON_VI_ID)';
    END IF;
END;
/