-- Redesign camera tables to Group B schema with KY_BAO_CAO_CODE and code-based dimensions.

DECLARE
    v_count NUMBER;
BEGIN
    -- Drop old FK from CAMERA_THUC_TRANG to CAMERA_QUAN_LY if exists.
    SELECT COUNT(*) INTO v_count
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'BIZ_CAMERA_THUC_TRANG'
      AND CONSTRAINT_NAME = 'FK_BIZ_CAMERA_THUC_TRANG_CAMERA_QUAN_LY';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP CONSTRAINT FK_BIZ_CAMERA_THUC_TRANG_CAMERA_QUAN_LY';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    -- Drop old index for CAMERA_QUAN_LY foreign key in CAMERA_THUC_TRANG if exists.
    SELECT COUNT(*) INTO v_count
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'IX_BIZ_CAMERA_THUC_TRANG_CAMERA_QUAN_LY_ID';

    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_CAMERA_THUC_TRANG_CAMERA_QUAN_LY_ID';
    END IF;
END;
/

-- CAMERA_QUAN_LY: remove legacy columns.
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_CAMERA_QUAN_LY' AND COLUMN_NAME = 'HE_THONG_CAMERA';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_QUAN_LY DROP COLUMN HE_THONG_CAMERA'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_CAMERA_QUAN_LY' AND COLUMN_NAME = 'SO_DIEM_LAP_DAT';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_QUAN_LY DROP COLUMN SO_DIEM_LAP_DAT'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_CAMERA_QUAN_LY' AND COLUMN_NAME = 'SO_CAMERA_TONG';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_QUAN_LY DROP COLUMN SO_CAMERA_TONG'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_CAMERA_QUAN_LY' AND COLUMN_NAME = 'CO_LUU_TRU_TAP_TRUNG';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_QUAN_LY DROP COLUMN CO_LUU_TRU_TAP_TRUNG'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_CAMERA_QUAN_LY' AND COLUMN_NAME = 'NHA_CUNG_CAP';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_QUAN_LY DROP COLUMN NHA_CUNG_CAP'; END IF;
END;
/

-- CAMERA_QUAN_LY: add redesigned columns.
ALTER TABLE BIZ_CAMERA_QUAN_LY ADD (
    KY_BAO_CAO_CODE      VARCHAR2(50) NOT NULL,
    NHOM_CAMERA          VARCHAR2(50),
    TEN_DON_VI_DIA_CHI   VARCHAR2(300) NOT NULL,
    BUONG_GIAM_TRANG_BI_SL NUMBER(10) DEFAULT 0 NOT NULL,
    BUONG_GIAM_TRANG_BI_TS NUMBER(10) DEFAULT 0 NOT NULL,
    NHU_CAU_DAU_TU       NUMBER(10) DEFAULT 0 NOT NULL,
    BAO_TRI              NUMBER(10) DEFAULT 0 NOT NULL,
    SUA_CHUA             NUMBER(10) DEFAULT 0 NOT NULL,
    SO_LAN_VI_PHAM       NUMBER(10) DEFAULT 0 NOT NULL,
    KET_NOI_CHIA_SE      VARCHAR2(200),
    HO_SO_CAP_DO_ATTT    NUMBER(10) DEFAULT 0 NOT NULL,
    CB_CHUYEN_TRACH      NUMBER(10) DEFAULT 0 NOT NULL,
    CB_KIEM_NHIEM        NUMBER(10) DEFAULT 0 NOT NULL,
    CB_DIA_PHUONG        NUMBER(10) DEFAULT 0 NOT NULL,
    DAO_TAO_BO           NUMBER(10) DEFAULT 0 NOT NULL,
    DAO_TAO_NHU_CAU      NUMBER(10) DEFAULT 0 NOT NULL
);

ALTER TABLE BIZ_CAMERA_QUAN_LY MODIFY (GHI_CHU VARCHAR2(2000));

-- CAMERA_THUC_TRANG: remove legacy columns.
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_CAMERA_THUC_TRANG' AND COLUMN_NAME = 'CAMERA_QUAN_LY_ID';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP COLUMN CAMERA_QUAN_LY_ID'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_CAMERA_THUC_TRANG' AND COLUMN_NAME = 'VI_TRI';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP COLUMN VI_TRI'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_CAMERA_THUC_TRANG' AND COLUMN_NAME = 'LOAI_CAMERA';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP COLUMN LOAI_CAMERA'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_CAMERA_THUC_TRANG' AND COLUMN_NAME = 'DO_PHAN_GIAI';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP COLUMN DO_PHAN_GIAI'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_CAMERA_THUC_TRANG' AND COLUMN_NAME = 'TINH_TRANG';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP COLUMN TINH_TRANG'; END IF;
END;
/

-- CAMERA_THUC_TRANG: add redesigned columns.
ALTER TABLE BIZ_CAMERA_THUC_TRANG ADD (
    KY_BAO_CAO_CODE      VARCHAR2(50) NOT NULL,
    NHOM_CAMERA          VARCHAR2(50),
    TEN_HE_THONG         VARCHAR2(300) NOT NULL,
    CAU_HINH_IP          NUMBER(10) DEFAULT 0 NOT NULL,
    CAU_HINH_ANALOG      NUMBER(10) DEFAULT 0 NOT NULL,
    THUC_TRANG_IP        NUMBER(10) DEFAULT 0 NOT NULL,
    THUC_TRANG_ANALOG    NUMBER(10) DEFAULT 0 NOT NULL,
    CHU_DAU_TU           VARCHAR2(200),
    NAM_DAU_TU           NUMBER(4),
    DUONG_TRUYEN         VARCHAR2(50),
    PHAN_MEM             VARCHAR2(200),
    LUU_TRU              VARCHAR2(200)
);

ALTER TABLE BIZ_CAMERA_THUC_TRANG MODIFY (GHI_CHU VARCHAR2(2000));

CREATE INDEX IX_BIZ_CAMERA_QUAN_LY_DON_VI_KY
    ON BIZ_CAMERA_QUAN_LY (DON_VI_ID, KY_BAO_CAO_CODE);

CREATE INDEX IX_BIZ_CAMERA_THUC_TRANG_DON_VI_KY
    ON BIZ_CAMERA_THUC_TRANG (DON_VI_ID, KY_BAO_CAO_CODE);
