-- Redesign BIZ_DU_AN_CNTT to align with Form 11 project reporting.

DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'MA_DU_AN';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN MA_DU_AN'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'LOAI_DU_AN';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN LOAI_DU_AN'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'NGAY_BAT_DAU';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN NGAY_BAT_DAU'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'NGAY_KET_THUC';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN NGAY_KET_THUC'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'TRANG_THAI';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN TRANG_THAI'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'MO_TA';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN MO_TA'; END IF;
END;
/

DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'DON_VI_THUC_HIEN';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT RENAME COLUMN DON_VI_THUC_HIEN TO DON_VI_CHU_TRI'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'TONG_MUC_DAU_TU';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT RENAME COLUMN TONG_MUC_DAU_TU TO TONG_KINH_PHI'; END IF;
END;
/

DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'TEN_DU_AN';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT MODIFY (TEN_DU_AN NVARCHAR2(500))'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'NGUON_VON';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT MODIFY (NGUON_VON NVARCHAR2(50))'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'GHI_CHU';
    IF v_count > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT MODIFY (GHI_CHU NVARCHAR2(2000))'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'NAM_TRIEN_KHAI';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT ADD (NAM_TRIEN_KHAI NUMBER(4) NULL)'; END IF;
END;
/
DECLARE v_count NUMBER; BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLS WHERE TABLE_NAME = 'BIZ_DU_AN_CNTT' AND COLUMN_NAME = 'NAM_DUA_VAO_SU_DUNG';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT ADD (NAM_DUA_VAO_SU_DUNG NUMBER(4) NULL)'; END IF;
END;
/