-- V36: Drop KY_BAO_CAO_CODE from BIZ_DAO_TAO_BOI_DUONG and BIZ_DAO_TAO_HOC_VIEN (warehouse refactor)
DECLARE
    v_count NUMBER;
BEGIN
    -- ===== BIZ_DAO_TAO_BOI_DUONG =====
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_BIZ_DTBD_DV_KY';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_DTBD_DV_KY';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_DAO_TAO_BOI_DUONG' AND COLUMN_NAME = 'KY_BAO_CAO_CODE';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG DROP COLUMN KY_BAO_CAO_CODE';
    END IF;

    -- ===== BIZ_DAO_TAO_HOC_VIEN =====
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'UX_BIZ_DTHV_DV_KY_ND';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX UX_BIZ_DTHV_DV_KY_ND';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_BIZ_DTHV_DV_KY';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_DTHV_DV_KY';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN' AND COLUMN_NAME = 'KY_BAO_CAO_CODE';
    IF v_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN KY_BAO_CAO_CODE';
    END IF;
END;
/