DECLARE
    v_column_count NUMBER := 0;
    v_index_count NUMBER := 0;
    v_null_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_column_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'BIZ_DAO_TAO_HOC_VIEN'
       AND COLUMN_NAME = 'KY_BAO_CAO_CODE';

    IF v_column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN ADD (KY_BAO_CAO_CODE NVARCHAR2(50))';
    END IF;

    UPDATE BIZ_DAO_TAO_HOC_VIEN
       SET KY_BAO_CAO_CODE = TO_NCHAR(NAM) || TO_NCHAR('Q4')
     WHERE KY_BAO_CAO_CODE IS NULL
       AND NAM IS NOT NULL;

    UPDATE BIZ_DAO_TAO_HOC_VIEN
       SET KY_BAO_CAO_CODE = TO_NCHAR(EXTRACT(YEAR FROM SYSTIMESTAMP)) || TO_NCHAR('Q1')
     WHERE KY_BAO_CAO_CODE IS NULL;

    SELECT COUNT(*)
      INTO v_null_count
      FROM BIZ_DAO_TAO_HOC_VIEN
     WHERE KY_BAO_CAO_CODE IS NULL;

    IF v_null_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20038, 'V38 migration failed because some rows still have NULL KY_BAO_CAO_CODE');
    END IF;

    EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN MODIFY (KY_BAO_CAO_CODE NOT NULL)';

    BEGIN
        EXECUTE IMMEDIATE 'DROP INDEX UX_BIZ_DTHV_DV_NAM_ND';
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;

    SELECT COUNT(*)
      INTO v_index_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'UX_BIZ_DTHV_DV_KY_ND';

    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_BIZ_DTHV_DV_KY_ND ON BIZ_DAO_TAO_HOC_VIEN (DON_VI_ID, KY_BAO_CAO_CODE, NOI_DUNG_DAO_TAO)';
    END IF;
END;
/