-- V43: Remove KY_BAO_CAO_CODE from all BIZ_* business tables
-- Business tables represent current state of a unit, not period-bound snapshots.
-- The period link (KY_BAO_CAO_CODE) belongs only on snapshot tables.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN KY_BAO_CAO_CODE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_DAU_TU DROP COLUMN KY_BAO_CAO_CODE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_QUAN_LY DROP COLUMN KY_BAO_CAO_CODE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN KY_BAO_CAO_CODE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN KY_BAO_CAO_CODE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC DROP COLUMN KY_BAO_CAO_CODE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP COLUMN KY_BAO_CAO_CODE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO DROP COLUMN KY_BAO_CAO_CODE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_SOC DROP COLUMN KY_BAO_CAO_CODE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_VAN_BAN_QPPL DROP COLUMN KY_BAO_CAO_CODE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF;
END;
/
