-- V45: Add snapshot-in-place columns for BIZ_DAO_TAO_BOI_DUONG
-- and SCD2 columns for BIZ_NHAN_LUC_CNTT.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG ADD (
    KY_BAO_CAO_CODE NVARCHAR2(50),
    IS_LATEST NUMBER(1) DEFAULT 1 NOT NULL,
    SNAPSHOT_VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    SNAPSHOT_CREATED_AT TIMESTAMP NULL,
    SNAPSHOT_BATCH_ID NUMBER(19) NULL
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_BIZ_DTBD_DONVI_LATEST ON BIZ_DAO_TAO_BOI_DUONG (DON_VI_ID, IS_LATEST)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_BIZ_DTBD_DONVI_KY ON BIZ_DAO_TAO_BOI_DUONG (DON_VI_ID, KY_BAO_CAO_CODE)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NHAN_LUC_CNTT ADD (
    NHAN_SU_KEY NVARCHAR2(36),
    KY_BAO_CAO_CODE NVARCHAR2(50),
    VALID_FROM TIMESTAMP,
    VALID_TO TIMESTAMP NULL,
    IS_CURRENT NUMBER(1) DEFAULT 1,
    VERSION_NO NUMBER(10) DEFAULT 1
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

UPDATE BIZ_NHAN_LUC_CNTT
SET
  NHAN_SU_KEY = NVL(NHAN_SU_KEY, RAWTOHEX(SYS_GUID())),
  VALID_FROM = NVL(VALID_FROM, NVL(CREATED_AT, SYSTIMESTAMP)),
  IS_CURRENT = NVL(IS_CURRENT, 1),
  VERSION_NO = NVL(VERSION_NO, 1);

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NHAN_LUC_CNTT MODIFY (NHAN_SU_KEY NVARCHAR2(36) NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NHAN_LUC_CNTT MODIFY (VALID_FROM TIMESTAMP NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NHAN_LUC_CNTT MODIFY (IS_CURRENT NUMBER(1) DEFAULT 1 NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NHAN_LUC_CNTT MODIFY (VERSION_NO NUMBER(10) DEFAULT 1 NOT NULL)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1442 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_BIZ_NLC_DONVI_CURRENT ON BIZ_NHAN_LUC_CNTT (DON_VI_ID, IS_CURRENT)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_BIZ_NLC_KEY_CURRENT ON BIZ_NHAN_LUC_CNTT (NHAN_SU_KEY, IS_CURRENT)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_BIZ_NLC_KEY_VALID_RANGE ON BIZ_NHAN_LUC_CNTT (NHAN_SU_KEY, VALID_FROM, VALID_TO)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_BIZ_NLC_KEY_VERSION ON BIZ_NHAN_LUC_CNTT (NHAN_SU_KEY, VERSION_NO)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
