-- V47: Align SCD2 model for BIZ_NHAN_LUC_CNTT
-- SCD2 in this module uses VALID_FROM/VALID_TO, no KY_BAO_CAO_CODE.

BEGIN
  DECLARE
    v_count NUMBER := 0;
  BEGIN
    SELECT COUNT(1)
      INTO v_count
      FROM USER_TAB_COLS
     WHERE TABLE_NAME = 'BIZ_NHAN_LUC_CNTT'
       AND COLUMN_NAME = 'KY_BAO_CAO_CODE';

    IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NHAN_LUC_CNTT DROP COLUMN KY_BAO_CAO_CODE';
    END IF;
  END;
END;
/

UPDATE BIZ_NHAN_LUC_CNTT
SET VALID_FROM = NVL(VALID_FROM, NVL(CREATED_AT, SYSTIMESTAMP)),
    IS_CURRENT = NVL(IS_CURRENT, 1),
    VERSION_NO = NVL(VERSION_NO, 1);

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NHAN_LUC_CNTT ADD CONSTRAINT CHK_NHAN_LUC_CNTT_CURRENT CHECK (IS_CURRENT IN (0, 1))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2264 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_NHAN_LUC_CNTT_KEY_CURRENT ON BIZ_NHAN_LUC_CNTT (NHAN_SU_KEY, IS_CURRENT)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_NHAN_LUC_CNTT_VALID ON BIZ_NHAN_LUC_CNTT (DON_VI_ID, VALID_FROM, VALID_TO)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
