-- V48: Snapshot-in-place alignment for DAO_TAO modules.
-- DTBD and DTHV may already have columns from previous migrations.
-- This migration guarantees required columns/indexes and adds them for DTNN.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG ADD (
    IS_LATEST NUMBER(1) DEFAULT 1 NOT NULL,
    SNAPSHOT_VERSION NUMBER(5) DEFAULT 0 NOT NULL,
    SNAPSHOT_CREATED_AT TIMESTAMP NULL,
    SNAPSHOT_BATCH_ID NUMBER(19) NULL,
    KY_BAO_CAO_CODE NVARCHAR2(50) NULL
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

UPDATE BIZ_DAO_TAO_BOI_DUONG SET IS_LATEST = NVL(IS_LATEST, 1);

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG ADD CONSTRAINT CHK_DAO_TAO_BOI_DUONG_LATEST CHECK (IS_LATEST IN (0, 1))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2264 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_DAO_TAO_BOI_DUONG_LATEST ON BIZ_DAO_TAO_BOI_DUONG (DON_VI_ID, IS_LATEST)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_DAO_TAO_BOI_DUONG_KY ON BIZ_DAO_TAO_BOI_DUONG (KY_BAO_CAO_CODE)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN ADD (
    IS_LATEST NUMBER(1) DEFAULT 1 NOT NULL,
    SNAPSHOT_VERSION NUMBER(5) DEFAULT 0 NOT NULL,
    SNAPSHOT_CREATED_AT TIMESTAMP NULL,
    SNAPSHOT_BATCH_ID NUMBER(19) NULL,
    KY_BAO_CAO_CODE NVARCHAR2(50) NULL
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

UPDATE BIZ_DAO_TAO_HOC_VIEN SET IS_LATEST = NVL(IS_LATEST, 1);

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN ADD CONSTRAINT CHK_DAO_TAO_HOC_VIEN_LATEST CHECK (IS_LATEST IN (0, 1))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2264 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_NUOC_NGOAI ADD (
    IS_LATEST NUMBER(1) DEFAULT 1 NOT NULL,
    SNAPSHOT_VERSION NUMBER(5) DEFAULT 0 NOT NULL,
    SNAPSHOT_CREATED_AT TIMESTAMP NULL,
    SNAPSHOT_BATCH_ID NUMBER(19) NULL,
    KY_BAO_CAO_CODE NVARCHAR2(50) NULL
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

UPDATE BIZ_DAO_TAO_NUOC_NGOAI SET IS_LATEST = NVL(IS_LATEST, 1);

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_NUOC_NGOAI ADD CONSTRAINT CHK_DAO_TAO_NUOC_NGOAI_LATEST CHECK (IS_LATEST IN (0, 1))';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2264 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_DAO_TAO_NUOC_NGOAI_LATEST ON BIZ_DAO_TAO_NUOC_NGOAI (DON_VI_ID, IS_LATEST)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_DAO_TAO_NUOC_NGOAI_KY ON BIZ_DAO_TAO_NUOC_NGOAI (KY_BAO_CAO_CODE)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
