-- V49: Drop BIZ_DAO_TAO_NUOC_NGOAI because the module is no longer managed.

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BIZ_DAO_TAO_NUOC_NGOAI CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
