-- V53: Xoa cac cot snapshot khoi bang live Group P.
-- Du lieu da duoc migrate sang _HIS o V52.
-- Sau migration nay: bang live chi chua du lieu hien hanh (khong co IS_LATEST, KY_BAO_CAO_CODE, v.v.)

-- Helper: xoa index neu ton tai
-- ============================================================
-- BIZ_DAO_TAO_BOI_DUONG
-- ============================================================
DELETE FROM BIZ_DAO_TAO_BOI_DUONG WHERE IS_LATEST = 0;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_DTBD_DONVI_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_DTBD_DONVI_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG DROP COLUMN IS_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG DROP COLUMN SNAPSHOT_VERSION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG DROP COLUMN SNAPSHOT_CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG DROP COLUMN SNAPSHOT_BATCH_ID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_BOI_DUONG DROP COLUMN KY_BAO_CAO_CODE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

-- ============================================================
-- BIZ_DAO_TAO_HOC_VIEN
-- ============================================================
DELETE FROM BIZ_DAO_TAO_HOC_VIEN WHERE IS_LATEST = 0;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_DAO_TAO_HOC_VIEN_DONVI_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_DAO_TAO_HOC_VIEN_DONVI_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN IS_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN SNAPSHOT_VERSION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN SNAPSHOT_CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN SNAPSHOT_BATCH_ID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DAO_TAO_HOC_VIEN DROP COLUMN KY_BAO_CAO_CODE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

-- ============================================================
-- BIZ_NANG_LUC_SO
-- ============================================================
DELETE FROM BIZ_NANG_LUC_SO WHERE IS_LATEST = 0;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_NANG_LUC_SO_DONVI_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_NANG_LUC_SO_DONVI_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO DROP COLUMN IS_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO DROP COLUMN SNAPSHOT_VERSION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO DROP COLUMN SNAPSHOT_CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO DROP COLUMN SNAPSHOT_BATCH_ID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_NANG_LUC_SO DROP COLUMN KY_BAO_CAO_CODE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

-- ============================================================
-- BIZ_VAN_BAN_QPPL
-- ============================================================
DELETE FROM BIZ_VAN_BAN_QPPL WHERE IS_LATEST = 0;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_VAN_BAN_QPPL_DONVI_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_VAN_BAN_QPPL_DONVI_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_VAN_BAN_QPPL DROP COLUMN IS_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_VAN_BAN_QPPL DROP COLUMN SNAPSHOT_VERSION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_VAN_BAN_QPPL DROP COLUMN SNAPSHOT_CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_VAN_BAN_QPPL DROP COLUMN SNAPSHOT_BATCH_ID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_VAN_BAN_QPPL DROP COLUMN KY_BAO_CAO_CODE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

-- ============================================================
-- BIZ_DU_AN_CNTT
-- ============================================================
DELETE FROM BIZ_DU_AN_CNTT WHERE IS_LATEST = 0;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_DU_AN_CNTT_DONVI_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_DU_AN_CNTT_DONVI_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN IS_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN SNAPSHOT_VERSION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN SNAPSHOT_CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN SNAPSHOT_BATCH_ID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_DU_AN_CNTT DROP COLUMN KY_BAO_CAO_CODE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

-- ============================================================
-- BIZ_GIAM_SAT_SOC
-- ============================================================
DELETE FROM BIZ_GIAM_SAT_SOC WHERE IS_LATEST = 0;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_GIAM_SAT_SOC_DONVI_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_GIAM_SAT_SOC_DONVI_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_SOC DROP COLUMN IS_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_SOC DROP COLUMN SNAPSHOT_VERSION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_SOC DROP COLUMN SNAPSHOT_CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_SOC DROP COLUMN SNAPSHOT_BATCH_ID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_SOC DROP COLUMN KY_BAO_CAO_CODE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

-- ============================================================
-- BIZ_GIAM_SAT_NOC
-- ============================================================
DELETE FROM BIZ_GIAM_SAT_NOC WHERE IS_LATEST = 0;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_GIAM_SAT_NOC_DONVI_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_GIAM_SAT_NOC_DONVI_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC DROP COLUMN IS_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC DROP COLUMN SNAPSHOT_VERSION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC DROP COLUMN SNAPSHOT_CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC DROP COLUMN SNAPSHOT_BATCH_ID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC DROP COLUMN KY_BAO_CAO_CODE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

-- ============================================================
-- BIZ_ATTT_HTTT_VAN_HANH
-- ============================================================
DELETE FROM BIZ_ATTT_HTTT_VAN_HANH WHERE IS_LATEST = 0;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_ATTT_HTTT_VAN_HANH_DONVI_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_ATTT_HTTT_VAN_HANH_DONVI_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN IS_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN SNAPSHOT_VERSION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN SNAPSHOT_CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN SNAPSHOT_BATCH_ID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH DROP COLUMN KY_BAO_CAO_CODE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

-- ============================================================
-- BIZ_ATTT_HTTT_DAU_TU
-- ============================================================
DELETE FROM BIZ_ATTT_HTTT_DAU_TU WHERE IS_LATEST = 0;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_ATTT_HTTT_DAU_TU_DONVI_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_ATTT_HTTT_DAU_TU_DONVI_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_DAU_TU DROP COLUMN IS_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_DAU_TU DROP COLUMN SNAPSHOT_VERSION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_DAU_TU DROP COLUMN SNAPSHOT_CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_DAU_TU DROP COLUMN SNAPSHOT_BATCH_ID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_ATTT_HTTT_DAU_TU DROP COLUMN KY_BAO_CAO_CODE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

-- ============================================================
-- BIZ_CAMERA_QUAN_LY
-- ============================================================
DELETE FROM BIZ_CAMERA_QUAN_LY WHERE IS_LATEST = 0;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_CAMERA_QUAN_LY_DONVI_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_CAMERA_QUAN_LY_DONVI_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_QUAN_LY DROP COLUMN IS_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_QUAN_LY DROP COLUMN SNAPSHOT_VERSION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_QUAN_LY DROP COLUMN SNAPSHOT_CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_QUAN_LY DROP COLUMN SNAPSHOT_BATCH_ID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_QUAN_LY DROP COLUMN KY_BAO_CAO_CODE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

-- ============================================================
-- BIZ_CAMERA_THUC_TRANG
-- ============================================================
DELETE FROM BIZ_CAMERA_THUC_TRANG WHERE IS_LATEST = 0;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_CAMERA_THUC_TRANG_DONVI_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IX_BIZ_CAMERA_THUC_TRANG_DONVI_KY'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP COLUMN IS_LATEST'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP COLUMN SNAPSHOT_VERSION'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP COLUMN SNAPSHOT_CREATED_AT'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP COLUMN SNAPSHOT_BATCH_ID'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_CAMERA_THUC_TRANG DROP COLUMN KY_BAO_CAO_CODE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

-- Cap nhat thu tuc PRC_MARK_SNAPSHOT_IN_PLACE thanh stub (da thay the bang copy-to-HIS o application layer)
CREATE OR REPLACE PROCEDURE PRC_MARK_SNAPSHOT_IN_PLACE (
  P_KY_BAO_CAO_CODE   IN NVARCHAR2,
  P_SNAPSHOT_BATCH_ID IN NUMBER,
  P_DON_VI_ID         IN NUMBER DEFAULT NULL
) AS
BEGIN
  -- Replaced by application-layer copy-to-HIS logic (V53 refactor).
  NULL;
END;
/

CREATE OR REPLACE PROCEDURE PRC_ROLLUP_XA_PHUONG_SNAPSHOT (
  P_KY_BAO_CAO_CODE IN NVARCHAR2,
  P_DON_VI_ID       IN NUMBER
) AS
BEGIN
  -- Replaced by BaoCaoSnapshot aggregation logic (V53 refactor).
  NULL;
END;
/
