-- V58: Xoa SNAPSHOT_JSON, SUMMARY_JSON, BREAKDOWN_JSON khoi RPT_BAO_CAO_SNAPSHOT.
-- Cac bang _HIS voi KY_BAO_CAO_CODE la nguon du lieu chinh xac theo ky.
-- RPT_BAO_CAO_SNAPSHOT chi giu metadata trang thai nop (TrangThai, PhienBan, SubmittedAt, LockedAt, GhiChu).

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE RPT_BAO_CAO_SNAPSHOT DROP COLUMN SNAPSHOT_JSON';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE RPT_BAO_CAO_SNAPSHOT DROP COLUMN SUMMARY_JSON';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE RPT_BAO_CAO_SNAPSHOT DROP COLUMN BREAKDOWN_JSON';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_MARK_SNAPSHOT_IN_PLACE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_ROLLUP_XA_PHUONG_SNAPSHOT';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -4043 THEN RAISE; END IF; END;
/
