-- V59: Xoa SUMMARY_JSON va AGGREGATE_ROWS khoi RPT_SNAPSHOT_BATCH.
-- Hai cot nay la tan du tu thoi PRC_ROLLUP_XA_PHUONG_SNAPSHOT (da xoa o V58).
-- Hien tai khong co code nao ghi gia tri vao 2 cot nay.

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE RPT_SNAPSHOT_BATCH DROP COLUMN SUMMARY_JSON';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE RPT_SNAPSHOT_BATCH DROP COLUMN AGGREGATE_ROWS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
