-- V63: increase TEN_HE_THONG max length from 1000 to 2000 for multi-line text support

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_HTTT_TIEU_CHUAN MODIFY TEN_HE_THONG NVARCHAR2(2000)';
  EXECUTE IMMEDIATE 'ALTER TABLE BIZ_HTTT_TIEU_CHUAN_HIS MODIFY TEN_HE_THONG NVARCHAR2(2000)';
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    RAISE;
END;
/
