-- V67: Replace NAM_THANH_LAP + SO_NHAN_SU with TONG_SO_DOI_TUONG + SO_DA_GIAM_SAT
-- on BIZ_GIAM_SAT_NOC and BIZ_GIAM_SAT_NOC_HIS per bieu mau so 8 (NOC section)

-- Live table
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC DROP COLUMN NAM_THANH_LAP'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC DROP COLUMN SO_NHAN_SU'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC ADD TONG_SO_DOI_TUONG NUMBER(10,0) DEFAULT 0 NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC ADD SO_DA_GIAM_SAT NUMBER(10,0) DEFAULT 0 NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

-- History table
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC_HIS DROP COLUMN NAM_THANH_LAP'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC_HIS DROP COLUMN SO_NHAN_SU'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -904 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC_HIS ADD TONG_SO_DOI_TUONG NUMBER(10,0) DEFAULT 0 NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BIZ_GIAM_SAT_NOC_HIS ADD SO_DA_GIAM_SAT NUMBER(10,0) DEFAULT 0 NOT NULL'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
