-- V68: Add LOAI_HA_TANG column to BIZ_ATTT_HTTT_VAN_HANH and _HIS
-- Groups ATTT records by infrastructure type: BCANET / INTERNET / KHAC

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH
        ADD (LOAI_HA_TANG NVARCHAR2(20))
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH_HIS
        ADD (LOAI_HA_TANG NVARCHAR2(20))
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
