-- V6: Normalize internal timestamp column naming to Vietnam-time standard (no _UTC suffix)
-- Assumption: all stored values are interpreted as Vietnam time (UTC+7).

-- Identity
ALTER TABLE IDM_USERS RENAME COLUMN LAST_LOGIN_AT_UTC TO LAST_LOGIN_AT;
ALTER TABLE IDM_USERS RENAME COLUMN DELETED_AT_UTC TO DELETED_AT;
ALTER TABLE IDM_USERS RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE IDM_USERS RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

ALTER TABLE IDM_ROLES RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE IDM_ROLES RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

ALTER TABLE IDM_USER_ROLE_ASSIGNMENTS RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;

-- Organization
ALTER TABLE ORG_LOAI_DON_VI RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE ORG_LOAI_DON_VI RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

ALTER TABLE ORG_DON_VI RENAME COLUMN DELETED_AT_UTC TO DELETED_AT;
ALTER TABLE ORG_DON_VI RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE ORG_DON_VI RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

ALTER TABLE ORG_DANH_MUC RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE ORG_DANH_MUC RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

-- Reporting
ALTER TABLE RPT_KY_BAO_CAO RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE RPT_KY_BAO_CAO RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

ALTER TABLE RPT_KY_TRANG_THAI_DON_VI RENAME COLUMN NGAY_XAC_NHAN_UTC TO NGAY_XAC_NHAN;
ALTER TABLE RPT_KY_TRANG_THAI_DON_VI RENAME COLUMN NGAY_MO_LAI_UTC TO NGAY_MO_LAI;
ALTER TABLE RPT_KY_TRANG_THAI_DON_VI RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE RPT_KY_TRANG_THAI_DON_VI RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

ALTER TABLE RPT_BAO_CAO_SNAPSHOT RENAME COLUMN SUBMITTED_AT_UTC TO SUBMITTED_AT;
ALTER TABLE RPT_BAO_CAO_SNAPSHOT RENAME COLUMN LOCKED_AT_UTC TO LOCKED_AT;
ALTER TABLE RPT_BAO_CAO_SNAPSHOT RENAME COLUMN DELETED_AT_UTC TO DELETED_AT;
ALTER TABLE RPT_BAO_CAO_SNAPSHOT RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE RPT_BAO_CAO_SNAPSHOT RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

ALTER TABLE RPT_BAO_CAO_FILE RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE RPT_BAO_CAO_FILE RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

ALTER TABLE RPT_YEU_CAU_BO_SUNG RENAME COLUMN REQUESTED_AT_UTC TO REQUESTED_AT;
ALTER TABLE RPT_YEU_CAU_BO_SUNG RENAME COLUMN APPROVED_AT_UTC TO APPROVED_AT;
ALTER TABLE RPT_YEU_CAU_BO_SUNG RENAME COLUMN COMPLETED_AT_UTC TO COMPLETED_AT;

-- Documents / notification / audit
ALTER TABLE DOC_FILE_DINH_KEM RENAME COLUMN UPLOADED_AT_UTC TO UPLOADED_AT;
ALTER TABLE DOC_FILE_DINH_KEM RENAME COLUMN DELETED_AT_UTC TO DELETED_AT;
ALTER TABLE DOC_FILE_DINH_KEM RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE DOC_FILE_DINH_KEM RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

ALTER TABLE SYS_THONG_BAO RENAME COLUMN DOC_LUC_UTC TO DOC_LUC;
ALTER TABLE SYS_THONG_BAO RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;

ALTER TABLE AUD_SYSTEM_LOG RENAME COLUMN LOGGED_AT_UTC TO LOGGED_AT;

-- Business
ALTER TABLE BIZ_NHAN_LUC_CNTT RENAME COLUMN DELETED_AT_UTC TO DELETED_AT;
ALTER TABLE BIZ_NHAN_LUC_CNTT RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE BIZ_NHAN_LUC_CNTT RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

ALTER TABLE BIZ_HE_THONG_THONG_TIN RENAME COLUMN DELETED_AT_UTC TO DELETED_AT;
ALTER TABLE BIZ_HE_THONG_THONG_TIN RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE BIZ_HE_THONG_THONG_TIN RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

ALTER TABLE BIZ_DU_AN_CNTT RENAME COLUMN DELETED_AT_UTC TO DELETED_AT;
ALTER TABLE BIZ_DU_AN_CNTT RENAME COLUMN CREATED_AT_UTC TO CREATED_AT;
ALTER TABLE BIZ_DU_AN_CNTT RENAME COLUMN UPDATED_AT_UTC TO UPDATED_AT;

-- Rename audit index for clarity
DROP INDEX IX_SYSTEM_LOG_LOGGED_AT_UTC;
CREATE INDEX IX_AUD_SYSTEM_LOG_LOGGED_AT ON AUD_SYSTEM_LOG (LOGGED_AT);
