-- V71: Cập nhật tên vai trò tiếng Việt có dấu cho môi trường không chạy seeder.
-- Dùng từng UPDATE theo NORMALIZED_NAME để tránh lỗi trộn charset trong CASE/COALESCE.

UPDATE IDM_ROLES
SET TEN_ROLE = UNISTR('Qu\1EA3n tr\1ECB h\1EC7 th\1ED1ng')
WHERE NORMALIZED_NAME = 'SYSTEM_ADMIN';

UPDATE IDM_ROLES
SET TEN_ROLE = UNISTR('Qu\1EA3n l\00FD')
WHERE NORMALIZED_NAME = 'QUAN_LY';

UPDATE IDM_ROLES
SET TEN_ROLE = UNISTR('Ng\01B0\1EDDi d\00F9ng c\1EA5p t\1EC9nh')
WHERE NORMALIZED_NAME = 'CAP_TINH';

UPDATE IDM_ROLES
SET TEN_ROLE = UNISTR('Ng\01B0\1EDDi d\00F9ng c\1EA5p x\00E3')
WHERE NORMALIZED_NAME = 'CAP_XA';

UPDATE IDM_ROLES
SET TEN_ROLE = UNISTR('Ng\01B0\1EDDi xem')
WHERE NORMALIZED_NAME = 'VIEWER';

UPDATE IDM_ROLES
SET TEN_ROLE = UNISTR('L\00E3nh \0111\1EA1o')
WHERE NORMALIZED_NAME = 'LANH_DAO';
