-- V76: Bang co xac nhan cua don vi con tai thoi diem nop (che do TONG_HOP, PA3).
-- Thay the huong BREAKDOWN_JSON (da bo tu V58). Du lieu chi tiet don vi con nam o cac bang _HIS.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM ALL_TABLES
     WHERE TABLE_NAME = 'RPT_SNAPSHOT_XAC_NHAN';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE RPT_SNAPSHOT_XAC_NHAN (
                ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                SNAPSHOT_ID NUMBER(19) NOT NULL,
                DON_VI_ID NUMBER(19) NOT NULL,
                DA_XAC_NHAN NUMBER(1) DEFAULT 0 NOT NULL,
                XAC_NHAN_AT TIMESTAMP NULL,
                CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                CREATED_BY NUMBER(19) NULL,
                UPDATED_BY NUMBER(19) NULL,
                CONSTRAINT FK_RPT_SNAP_XN_SNAPSHOT
                    FOREIGN KEY (SNAPSHOT_ID) REFERENCES RPT_BAO_CAO_SNAPSHOT (ID) ON DELETE CASCADE,
                CONSTRAINT FK_RPT_SNAP_XN_DON_VI
                    FOREIGN KEY (DON_VI_ID) REFERENCES REF_DON_VI (ID)
            )';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM ALL_INDEXES
     WHERE INDEX_NAME = 'UX_RPT_SNAP_XN_SNAP_DONVI';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_RPT_SNAP_XN_SNAP_DONVI ON RPT_SNAPSHOT_XAC_NHAN (SNAPSHOT_ID, DON_VI_ID)';
    END IF;
END;
/

COMMENT ON TABLE RPT_SNAPSHOT_XAC_NHAN IS 'Co xac nhan cua tung don vi con tai thoi diem don vi cha (TONG_HOP) nop bao cao.';
COMMENT ON COLUMN RPT_SNAPSHOT_XAC_NHAN.DA_XAC_NHAN IS '0/1 - trang thai DA_XAC_NHAN cua don vi con luc chot snapshot.';
