-- V8: Migrate data from ORG_DANH_MUC (generic) to CODES/CODE_VALUES

MERGE INTO CODES c
USING (
    SELECT
        NHOM_CODE,
        INITCAP(REPLACE(NHOM_CODE, '_', ' ')) AS GROUP_NAME,
        MIN(CREATED_AT) AS CREATED_AT,
        MAX(UPDATED_AT) AS UPDATED_AT,
        MIN(CREATED_BY) AS CREATED_BY,
        MAX(UPDATED_BY) AS UPDATED_BY
    FROM ORG_DANH_MUC
    GROUP BY NHOM_CODE
) s
ON (c.CODE = s.NHOM_CODE)
WHEN MATCHED THEN
    UPDATE SET
        c.NAME = s.GROUP_NAME,
        c.UPDATED_AT = NVL(s.UPDATED_AT, SYSTIMESTAMP),
        c.UPDATED_BY = s.UPDATED_BY
WHEN NOT MATCHED THEN
    INSERT (CODE, NAME, DESCRIPTION, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY)
    VALUES (
        s.NHOM_CODE,
        s.GROUP_NAME,
        NULL,
        0,
        1,
        0,
        NVL(s.CREATED_AT, SYSTIMESTAMP),
        NVL(s.UPDATED_AT, SYSTIMESTAMP),
        s.CREATED_BY,
        s.UPDATED_BY
    );

MERGE INTO CODE_VALUES v
USING (
    SELECT
        c.ID AS CODE_ID,
        d.ITEM_CODE AS VALUE,
        d.TEN_HIEN_THI AS NAME,
        d.MO_TA AS DESCRIPTION,
        NVL(d.THU_TU, 0) AS SORT_ORDER,
        NVL(d.IS_ACTIVE, 1) AS IS_ACTIVE,
        NVL(d.CREATED_AT, SYSTIMESTAMP) AS CREATED_AT,
        NVL(d.UPDATED_AT, SYSTIMESTAMP) AS UPDATED_AT,
        d.CREATED_BY AS CREATED_BY,
        d.UPDATED_BY AS UPDATED_BY
    FROM ORG_DANH_MUC d
    JOIN CODES c ON c.CODE = d.NHOM_CODE
) s
ON (v.CODE_ID = s.CODE_ID AND v.VALUE = s.VALUE)
WHEN MATCHED THEN
    UPDATE SET
        v.NAME = s.NAME,
        v.DESCRIPTION = s.DESCRIPTION,
        v.SORT_ORDER = s.SORT_ORDER,
        v.IS_ACTIVE = s.IS_ACTIVE,
        v.UPDATED_AT = s.UPDATED_AT,
        v.UPDATED_BY = s.UPDATED_BY
WHEN NOT MATCHED THEN
    INSERT (CODE_ID, VALUE, NAME, DESCRIPTION, SORT_ORDER, IS_ACTIVE, IS_SYSTEM, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY)
    VALUES (
        s.CODE_ID,
        s.VALUE,
        s.NAME,
        s.DESCRIPTION,
        s.SORT_ORDER,
        s.IS_ACTIVE,
        0,
        s.CREATED_AT,
        s.UPDATED_AT,
        s.CREATED_BY,
        s.UPDATED_BY
    );
