ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH ADD (
    TRANG_THAI_TRIEN_KHAI_PHUONG_AN VARCHAR2(40 CHAR),
    NOI_DUNG_PHUONG_AN_DA_TRIEN_KHAI VARCHAR2(2000 CHAR)
);

ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH_HIS ADD (
    TRANG_THAI_TRIEN_KHAI_PHUONG_AN VARCHAR2(40 CHAR),
    NOI_DUNG_PHUONG_AN_DA_TRIEN_KHAI VARCHAR2(2000 CHAR)
);

ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH MODIFY (
    CHU_QUAN VARCHAR2(300 CHAR),
    DON_VI_VAN_HANH VARCHAR2(300 CHAR)
);

ALTER TABLE BIZ_ATTT_HTTT_VAN_HANH_HIS MODIFY (
    CHU_QUAN VARCHAR2(300 CHAR),
    DON_VI_VAN_HANH VARCHAR2(300 CHAR)
);

UPDATE BIZ_ATTT_HTTT_VAN_HANH
SET TRANG_THAI_TRIEN_KHAI_PHUONG_AN = CASE
    WHEN DA_TRIEN_KHAI_PHUONG_AN = 1 THEN 'DA_TRIEN_KHAI_DAY_DU'
    ELSE 'CHUA_TRIEN_KHAI'
END;

UPDATE BIZ_ATTT_HTTT_VAN_HANH_HIS
SET TRANG_THAI_TRIEN_KHAI_PHUONG_AN = CASE
    WHEN DA_TRIEN_KHAI_PHUONG_AN = 1 THEN 'DA_TRIEN_KHAI_DAY_DU'
    ELSE 'CHUA_TRIEN_KHAI'
END;
