ALTER TABLE BIZ_ATTT_HTTT_DAU_TU ADD (
    LOAI_HA_TANG VARCHAR2(20 CHAR) DEFAULT 'KHAC' NOT NULL
);

ALTER TABLE BIZ_ATTT_HTTT_DAU_TU_HIS ADD (
    LOAI_HA_TANG VARCHAR2(20 CHAR) DEFAULT 'KHAC' NOT NULL
);

ALTER TABLE BIZ_ATTT_HTTT_DAU_TU ADD CONSTRAINT CK_BIZ_ATTTDT_LOAI_HA_TANG
    CHECK (LOAI_HA_TANG IN ('BCANET', 'INTERNET', 'KHAC'));

ALTER TABLE BIZ_ATTT_HTTT_DAU_TU_HIS ADD CONSTRAINT CK_ATTTDT_HIS_LOAI_HA_TANG
    CHECK (LOAI_HA_TANG IN ('BCANET', 'INTERNET', 'KHAC'));
