export type BizFieldType =
  | 'text'
  | 'number'
  | 'decimal'
  | 'date'
  | 'checkbox'
  | 'select';

export interface BizFieldConfig {
  key: string;
  label: string;
  type: BizFieldType;
  codeKey?: string;
  required?: boolean;
  maxLength?: number;
  defaultValue?: string | number | boolean | null;
  showInTable?: boolean;
  managedByScope?: boolean;
}

export interface BizModuleConfig {
  moduleKey: string;
  routePath: string;
  endpoint: string;
  requiresKyBaoCaoCode?: boolean;
  bindDonViToAccount?: boolean;
  title: string;
  subtitle: string;
  navLabel: string;
  navIcon: string;
  permissions: {
    read: string;
    create: string;
    update: string;
    delete: string;
  };
  fields: BizFieldConfig[];
}

const donViField: BizFieldConfig = {
  key: 'donViId',
  label: 'Don vi ID',
  type: 'number',
  required: true,
  defaultValue: 2002,
  showInTable: false,
  managedByScope: true,
};

const kyBaoCaoField: BizFieldConfig = {
  key: 'kyBaoCaoCode',
  label: 'Ky bao cao',
  type: 'text',
  required: true,
  maxLength: 20,
  defaultValue: '2026Q1',
  showInTable: false,
  managedByScope: true,
};

const buildFields = (...fields: BizFieldConfig[]): BizFieldConfig[] => [
  donViField,
  kyBaoCaoField,
  ...fields,
];

const buildCurrentStateFields = (
  ...fields: BizFieldConfig[]
): BizFieldConfig[] => [donViField, ...fields];

const buildWarehouseFields = (...fields: BizFieldConfig[]): BizFieldConfig[] =>
  fields;

export const BIZ_MODULES: Record<string, BizModuleConfig> = {
  vanBanQppl: {
    moduleKey: 'vanBanQppl',
    routePath: 'van-ban-qppl',
    endpoint: 'van-ban-qppl',
    title: 'Van Ban QPPL',
    subtitle: 'Quan ly van ban quy pham phap luat theo ky bao cao.',
    navLabel: 'Van ban QPPL',
    navIcon: 'pi-book',
    permissions: {
      read: 'van_ban_qppl:read',
      create: 'van_ban_qppl:create',
      update: 'van_ban_qppl:update',
      delete: 'van_ban_qppl:delete',
    },
    fields: buildCurrentStateFields(
      {
        key: 'soHieu',
        label: 'So hieu',
        type: 'text',
        required: true,
        maxLength: 100,
        showInTable: true,
      },
      {
        key: 'tenVanBan',
        label: 'Ten van ban',
        type: 'text',
        maxLength: 500,
        showInTable: true,
      },
      {
        key: 'loaiVanBan',
        label: 'Loai van ban',
        type: 'text',
        maxLength: 100,
        showInTable: true,
      },
      {
        key: 'coQuanBanHanh',
        label: 'Co quan ban hanh',
        type: 'text',
        maxLength: 200,
      },
      {
        key: 'ngayBanHanh',
        label: 'Ngay ban hanh',
        type: 'date',
        required: true,
        showInTable: true,
      },
      { key: 'ngayHieuLuc', label: 'Ngay hieu luc', type: 'date' },
      { key: 'linhVuc', label: 'Linh vuc', type: 'text', maxLength: 100 },
      { key: 'trichYeu', label: 'Trich yeu', type: 'text', maxLength: 2000 },
      {
        key: 'tinhTrangTrienKhai',
        label: 'Tinh trang trien khai',
        type: 'select',
        codeKey: 'TINH_TRANG_TRIEN_KHAI_VB',
        showInTable: true,
      },
      { key: 'ghiChu', label: 'Ghi chu', type: 'text', maxLength: 500 },
    ),
  },
  daoTaoBoiDuong: {
    moduleKey: 'daoTaoBoiDuong',
    routePath: 'dao-tao-boi-duong',
    endpoint: 'dao-tao-boi-duong',
    requiresKyBaoCaoCode: false,
    bindDonViToAccount: true,
    title: 'Đào tạo bồi dưỡng',
    subtitle: 'Kho dữ liệu khóa học bồi dưỡng, tập huấn chuyên môn',
    navLabel: 'Đào tạo bồi dưỡng',
    navIcon: 'pi-users',
    permissions: {
      read: 'dao_tao_boi_duong:read',
      create: 'dao_tao_boi_duong:create',
      update: 'dao_tao_boi_duong:update',
      delete: 'dao_tao_boi_duong:delete',
    },
    fields: buildWarehouseFields(
      {
        key: 'tenKhoaHoc',
        label: 'Tên khóa học',
        type: 'text',
        required: true,
        maxLength: 300,
        showInTable: true,
      },
      {
        key: 'donViToChuc',
        label: 'Đơn vị tổ chức',
        type: 'text',
        required: true,
        maxLength: 200,
        showInTable: true,
      },
      {
        key: 'hinhThuc',
        label: 'Hình thức',
        type: 'text',
        maxLength: 100,
        defaultValue: null,
      },
      {
        key: 'soLuongHv',
        label: 'Số lượng học viên',
        type: 'number',
        defaultValue: null,
        showInTable: true,
      },
      {
        key: 'thoiGianTu',
        label: 'Thời gian từ',
        type: 'date',
      },
      {
        key: 'thoiGianDen',
        label: 'Thời gian đến',
        type: 'date',
      },
      { key: 'ghiChu', label: 'Ghi chú', type: 'text', maxLength: 500 },
    ),
  },
  daoTaoHocVien: {
    moduleKey: 'daoTaoHocVien',
    routePath: 'dao-tao-hoc-vien',
    endpoint: 'dao-tao-hoc-vien',
    requiresKyBaoCaoCode: false,
    bindDonViToAccount: true,
    title: 'Đào Tạo Học Viện',
    subtitle: 'Thống kê số liệu đào tạo tại học viện, nhà trường.',
    navLabel: 'Đào tạo học viện',
    navIcon: 'pi-building',
    permissions: {
      read: 'dao_tao_hoc_vien:read',
      create: 'dao_tao_hoc_vien:create',
      update: 'dao_tao_hoc_vien:update',
      delete: 'dao_tao_hoc_vien:delete',
    },
    fields: buildFields(
      {
        key: 'noiDungDaoTao',
        label: 'Nội dung đào tạo',
        type: 'select',
        codeKey: 'NOI_DUNG_DAO_TAO_HV',
        required: true,
        maxLength: 50,
        showInTable: true,
      },
      {
        key: 'soTienSi',
        label: 'Tiến sĩ',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'soThacSi',
        label: 'Thạc sĩ',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'soDaiHoc',
        label: 'Đại học',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'soCaoDang',
        label: 'Cao đẳng',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'soTrungCap',
        label: 'Trung cấp',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      { key: 'ghiChu', label: 'Ghi chú', type: 'text', maxLength: 500 },
    ),
  },
  nangLucSo: {
    moduleKey: 'nangLucSo',
    routePath: 'nang-luc-so',
    endpoint: 'nang-luc-so',
    title: 'Năng lực số',
    subtitle: 'Thống kê số liệu năng lực số theo nhóm vị trí của đơn vị.',
    navLabel: 'Năng lực số',
    navIcon: 'pi-chart-bar',
    permissions: {
      read: 'nang_luc_so:read',
      create: 'nang_luc_so:create',
      update: 'nang_luc_so:update',
      delete: 'nang_luc_so:delete',
    },
    fields: buildFields(
      {
        key: 'nhomViTri',
        label: 'Nhóm vị trí',
        type: 'select',
        codeKey: 'NHOM_NANG_LUC_SO',
        required: true,
        showInTable: true,
      },
      {
        key: 'tongSoDienDanhGia',
        label: 'Tổng số diện đánh giá',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'tongSoDat',
        label: 'Tổng số đạt',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'tongSoChuaDat',
        label: 'Tổng số chưa đạt',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      { key: 'ghiChu', label: 'Ghi chu', type: 'text', maxLength: 500 },
    ),
  },
  heThongThongTin: {
    moduleKey: 'heThongThongTin',
    routePath: 'he-thong-thong-tin',
    endpoint: 'he-thong-thong-tin',
    requiresKyBaoCaoCode: false,
    title: 'He Thong Thong Tin',
    subtitle: 'Quan ly cac he thong thong tin dang van hanh.',
    navLabel: 'He thong thong tin',
    navIcon: 'pi pi-server',
    permissions: {
      read: 'he_thong_thong_tin:read',
      create: 'he_thong_thong_tin:create',
      update: 'he_thong_thong_tin:update',
      delete: 'he_thong_thong_tin:delete',
    },
    fields: buildCurrentStateFields(
      {
        key: 'tenHeThong',
        label: 'Ten he thong',
        type: 'text',
        required: true,
        maxLength: 300,
        showInTable: true,
      },
      {
        key: 'maHeThong',
        label: 'Ma he thong',
        type: 'text',
        maxLength: 100,
        showInTable: true,
      },
      {
        key: 'loaiHeThong',
        label: 'Loai he thong',
        type: 'text',
        required: true,
        maxLength: 100,
        showInTable: true,
      },
      {
        key: 'trangThai',
        label: 'Trang thai',
        type: 'text',
        required: true,
        maxLength: 100,
        showInTable: true,
      },
    ),
  },
  duAnCntt: {
    moduleKey: 'duAnCntt',
    routePath: 'du-an-cntt',
    endpoint: 'du-an-cntt',
    requiresKyBaoCaoCode: false,
    title: 'Du An CNTT',
    subtitle: 'Thong ke du an dau tu, ung dung CNTT theo ky bao cao.',
    navLabel: 'Du an CNTT',
    navIcon: 'pi-briefcase',
    permissions: {
      read: 'du_an_cntt:read',
      create: 'du_an_cntt:create',
      update: 'du_an_cntt:update',
      delete: 'du_an_cntt:delete',
    },
    fields: buildFields(
      {
        key: 'tenDuAn',
        label: 'Ten de an/du an',
        type: 'text',
        required: true,
        maxLength: 500,
        showInTable: true,
      },
      {
        key: 'donViChuTri',
        label: 'Don vi chu tri trien khai',
        type: 'text',
        maxLength: 200,
        showInTable: true,
      },
      {
        key: 'namTrienKhai',
        label: 'Nam trien khai',
        type: 'number',
        showInTable: true,
      },
      {
        key: 'namDuaVaoSuDung',
        label: 'Nam dua vao su dung',
        type: 'number',
        showInTable: true,
      },
      {
        key: 'tongKinhPhi',
        label: 'Tong kinh phi (ty VND)',
        type: 'decimal',
        showInTable: true,
      },
      {
        key: 'nguonVon',
        label: 'Nguon von',
        type: 'select',
        codeKey: 'NGUON_VON_DU_AN',
        showInTable: true,
      },
      { key: 'ghiChu', label: 'Ghi chu', type: 'text', maxLength: 2000 },
    ),
  },
  haTangMang: {
    moduleKey: 'haTangMang',
    routePath: 'ha-tang-mang',
    endpoint: 'ha-tang-mang',
    requiresKyBaoCaoCode: false,
    title: 'Ha Tang Mang',
    subtitle: 'Quan ly thong tin ha tang ket noi mang.',
    navLabel: 'Ha tang mang',
    navIcon: 'pi-wifi',
    permissions: {
      read: 'ha_tang_mang:read',
      create: 'ha_tang_mang:create',
      update: 'ha_tang_mang:update',
      delete: 'ha_tang_mang:delete',
    },
    fields: buildCurrentStateFields(
      {
        key: 'loaiDvThongKe',
        label: 'Loai don vi thong ke',
        type: 'select',
        codeKey: 'LOAI_DV_THONG_KE_MANG',
        required: true,
        showInTable: true,
      },
      {
        key: 'soDonViTrucThuoc',
        label: 'So don vi truc thuoc',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'soDaKetNoiBcanet',
        label: 'So da ket noi BCANet',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'soDuongTruyenVnpt',
        label: 'So duong truyen VNPT',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'soDuongTruyenKhac',
        label: 'So duong truyen khac',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'soKetNoiInternet',
        label: 'So ket noi Internet',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      { key: 'ghiChu', label: 'Ghi chu', type: 'text', maxLength: 500 },
    ),
  },
  giamSatSoc: {
    moduleKey: 'giamSatSoc',
    routePath: 'giam-sat-soc',
    endpoint: 'giam-sat-soc',
    requiresKyBaoCaoCode: false,
    title: 'Giam Sat SOC',
    subtitle: 'Theo doi thong tin van hanh trung tam SOC.',
    navLabel: 'Giam sat SOC',
    navIcon: 'pi-shield',
    permissions: {
      read: 'giam_sat_soc:read',
      create: 'giam_sat_soc:create',
      update: 'giam_sat_soc:update',
      delete: 'giam_sat_soc:delete',
    },
    fields: buildCurrentStateFields(
      {
        key: 'coSoc',
        label: 'Co SOC',
        type: 'checkbox',
        required: true,
        defaultValue: false,
        showInTable: true,
      },
      { key: 'namThanhLap', label: 'Nam thanh lap', type: 'number' },
      {
        key: 'soNhanSu',
        label: 'So nhan su',
        type: 'number',
        showInTable: true,
      },
      {
        key: 'congCuSuDung',
        label: 'Cong cu su dung',
        type: 'text',
        maxLength: 500,
      },
      {
        key: 'soCanhBaoThang',
        label: 'So canh bao thang',
        type: 'number',
        showInTable: true,
      },
      { key: 'ghiChu', label: 'Ghi chu', type: 'text', maxLength: 500 },
    ),
  },
  giamSatNoc: {
    moduleKey: 'giamSatNoc',
    routePath: 'giam-sat-noc',
    endpoint: 'giam-sat-noc',
    requiresKyBaoCaoCode: false,
    title: 'Giam Sat NOC',
    subtitle: 'Theo doi thong tin giam sat va van hanh NOC.',
    navLabel: 'Giam sat NOC',
    navIcon: 'pi-server',
    permissions: {
      read: 'giam_sat_noc:read',
      create: 'giam_sat_noc:create',
      update: 'giam_sat_noc:update',
      delete: 'giam_sat_noc:delete',
    },
    fields: buildCurrentStateFields(
      {
        key: 'coNoc',
        label: 'Co NOC',
        type: 'checkbox',
        required: true,
        defaultValue: false,
        showInTable: true,
      },
      { key: 'namThanhLap', label: 'Nam thanh lap', type: 'number' },
      {
        key: 'soNhanSu',
        label: 'So nhan su',
        type: 'number',
        showInTable: true,
      },
      {
        key: 'phamViGiamSat',
        label: 'Pham vi giam sat',
        type: 'text',
        maxLength: 500,
        showInTable: true,
      },
      { key: 'ghiChu', label: 'Ghi chu', type: 'text', maxLength: 500 },
    ),
  },
  atttHtttVanHanh: {
    moduleKey: 'atttHtttVanHanh',
    routePath: 'attt-httt-van-hanh',
    endpoint: 'attt-httt-van-hanh',
    title: 'ATTT HTTT Van Hanh',
    subtitle:
      'Theo doi phe duyet va trien khai phuong an ATTT cho HTTT dang van hanh.',
    navLabel: 'ATTT van hanh',
    navIcon: 'pi-lock',
    permissions: {
      read: 'attt_httt_van_hanh:read',
      create: 'attt_httt_van_hanh:create',
      update: 'attt_httt_van_hanh:update',
      delete: 'attt_httt_van_hanh:delete',
    },
    fields: buildFields(
      {
        key: 'htttId',
        label: 'HTTT ID',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'chuQuan',
        label: 'Chu quan',
        type: 'text',
        maxLength: 200,
        showInTable: true,
      },
      {
        key: 'donViVanHanh',
        label: 'Don vi van hanh',
        type: 'text',
        maxLength: 200,
        showInTable: true,
      },
      {
        key: 'capDoDeXuat',
        label: 'Cap do de xuat',
        type: 'text',
        maxLength: 20,
        showInTable: true,
      },
      {
        key: 'tinhTrangPheDuyet',
        label: 'Tinh trang phe duyet',
        type: 'select',
        codeKey: 'TINH_TRANG_PHE_DUYET_ATTT',
        showInTable: true,
      },
      {
        key: 'quyetDinhPheDuyet',
        label: 'Quyet dinh phe duyet',
        type: 'text',
        maxLength: 200,
      },
      {
        key: 'quyCheAttt',
        label: 'Quy che ATTT',
        type: 'text',
        maxLength: 200,
      },
      {
        key: 'duKienNgayPheDuyet',
        label: 'Du kien ngay phe duyet',
        type: 'date',
      },
      {
        key: 'daTrienKhaiPhuongAn',
        label: 'Da trien khai PA',
        type: 'checkbox',
        required: true,
        defaultValue: false,
        showInTable: true,
      },
      {
        key: 'duKienNgayTrienKhai',
        label: 'Du kien ngay trien khai',
        type: 'date',
      },
      {
        key: 'kiemTraDanhGia',
        label: 'Kiem tra danh gia',
        type: 'text',
        maxLength: 500,
      },
      { key: 'ghiChu', label: 'Ghi chu', type: 'text', maxLength: 2000 },
    ),
  },
  atttHtttDauTu: {
    moduleKey: 'atttHtttDauTu',
    routePath: 'attt-httt-dau-tu',
    endpoint: 'attt-httt-dau-tu',
    title: 'ATTT HTTT Dau Tu',
    subtitle: 'Theo doi danh muc dau tu an toan thong tin.',
    navLabel: 'ATTT dau tu',
    navIcon: 'pi-wallet',
    permissions: {
      read: 'attt_httt_dau_tu:read',
      create: 'attt_httt_dau_tu:create',
      update: 'attt_httt_dau_tu:update',
      delete: 'attt_httt_dau_tu:delete',
    },
    fields: buildFields(
      {
        key: 'htttId',
        label: 'HTTT ID',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'chuQuan',
        label: 'Chu quan',
        type: 'text',
        maxLength: 200,
        showInTable: true,
      },
      {
        key: 'donViVanHanh',
        label: 'Don vi van hanh',
        type: 'text',
        maxLength: 200,
        showInTable: true,
      },
      {
        key: 'capDoDeXuat',
        label: 'Cap do de xuat',
        type: 'text',
        maxLength: 20,
        showInTable: true,
      },
      {
        key: 'ngayPheDuyetHsdxcd',
        label: 'Ngay phe duyet HSDXCD',
        type: 'date',
        showInTable: true,
      },
      {
        key: 'quyetDinhPheDuyet',
        label: 'Quyet dinh phe duyet',
        type: 'text',
        maxLength: 200,
        showInTable: true,
      },
      {
        key: 'daLongGhepThuyetMinh',
        label: 'Da long ghep thuyet minh',
        type: 'checkbox',
        required: true,
        defaultValue: false,
        showInTable: true,
      },
      { key: 'ghiChu', label: 'Ghi chu', type: 'text', maxLength: 2000 },
    ),
  },
  giaiPhapAttt: {
    moduleKey: 'giaiPhapAttt',
    routePath: 'giai-phap-attt',
    endpoint: 'giai-phap-attt',
    requiresKyBaoCaoCode: false,
    title: 'Giai Phap ATTT',
    subtitle: 'Ma tran giai phap an toan thong tin theo SL/TS.',
    navLabel: 'Giai phap ATTT',
    navIcon: 'pi-shield',
    permissions: {
      read: 'giai_phap_attt:read',
      create: 'giai_phap_attt:create',
      update: 'giai_phap_attt:update',
      delete: 'giai_phap_attt:delete',
    },
    fields: buildCurrentStateFields(
      {
        key: 'tenGiaiPhap',
        label: 'Ten giai phap',
        type: 'text',
        required: true,
        maxLength: 50,
        showInTable: true,
      },
      {
        key: 'mayTinhBcanetSl',
        label: 'May tinh BCANet (SL)',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'mayTinhBcanetTs',
        label: 'May tinh BCANet (TS)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'mayTinhInternetSl',
        label: 'May tinh Internet (SL)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'mayTinhInternetTs',
        label: 'May tinh Internet (TS)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'mayTinhLocalSl',
        label: 'May tinh Local (SL)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'mayTinhLocalTs',
        label: 'May tinh Local (TS)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'mayChuBcanetSl',
        label: 'May chu BCANet (SL)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'mayChuBcanetTs',
        label: 'May chu BCANet (TS)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'mayChuInternetSl',
        label: 'May chu Internet (SL)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'mayChuInternetTs',
        label: 'May chu Internet (TS)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'mayChuLocalSl',
        label: 'May chu Local (SL)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'mayChuLocalTs',
        label: 'May chu Local (TS)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      { key: 'ghiChu', label: 'Ghi chu', type: 'text', maxLength: 2000 },
    ),
  },
  cameraQuanLy: {
    moduleKey: 'cameraQuanLy',
    routePath: 'camera-quan-ly',
    endpoint: 'camera-quan-ly',
    requiresKyBaoCaoCode: false,
    title: 'Camera Quan Ly',
    subtitle: 'Cong tac quan ly he thong camera theo nhom va ky bao cao.',
    navLabel: 'Camera quan ly',
    navIcon: 'pi-video',
    permissions: {
      read: 'camera_quan_ly:read',
      create: 'camera_quan_ly:create',
      update: 'camera_quan_ly:update',
      delete: 'camera_quan_ly:delete',
    },
    fields: buildFields(
      {
        key: 'nhomCamera',
        label: 'Nhom camera',
        type: 'select',
        codeKey: 'NHOM_CAMERA',
        showInTable: true,
      },
      {
        key: 'tenDonViDiaChi',
        label: 'Ten don vi/dia chi',
        type: 'text',
        required: true,
        maxLength: 300,
        showInTable: true,
      },
      {
        key: 'buongGiamTrangBiSl',
        label: 'Buong giam/khu vuc da trang bi (SL)',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'buongGiamTrangBiTs',
        label: 'Buong giam/khu vuc tong so (TS)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'nhuCauDauTu',
        label: 'Nhu cau dau tu',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'baoTri',
        label: 'Bao tri',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'suaChua',
        label: 'Sua chua',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'soLanViPham',
        label: 'So lan vi pham',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'ketNoiChiaSe',
        label: 'Ket noi chia se',
        type: 'text',
        maxLength: 200,
      },
      {
        key: 'hoSoCapDoAttt',
        label: 'Ho so cap do ATTT da phe duyet',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'cbChuyenTrach',
        label: 'Can bo chuyen trach',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'cbKiemNhiem',
        label: 'Can bo kiem nhiem',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'cbDiaPhuong',
        label: 'Can bo dia phuong',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'daoTaoBo',
        label: 'Dao tao tap huan (Bo)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'daoTaoNhuCau',
        label: 'Dao tao tap huan (Nhu cau)',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      { key: 'ghiChu', label: 'Ghi chu', type: 'text', maxLength: 2000 },
    ),
  },
  cameraThucTrang: {
    moduleKey: 'cameraThucTrang',
    routePath: 'camera-thuc-trang',
    endpoint: 'camera-thuc-trang',
    requiresKyBaoCaoCode: false,
    title: 'Camera Thuc Trang',
    subtitle: 'Thuc trang dau tu, trang bi camera theo nhom va ky bao cao.',
    navLabel: 'Camera thuc trang',
    navIcon: 'pi-map-marker',
    permissions: {
      read: 'camera_thuc_trang:read',
      create: 'camera_thuc_trang:create',
      update: 'camera_thuc_trang:update',
      delete: 'camera_thuc_trang:delete',
    },
    fields: buildFields(
      {
        key: 'nhomCamera',
        label: 'Nhom camera',
        type: 'select',
        codeKey: 'NHOM_CAMERA',
        showInTable: true,
      },
      {
        key: 'tenHeThong',
        label: 'Ten he thong',
        type: 'text',
        required: true,
        maxLength: 300,
        showInTable: true,
      },
      {
        key: 'cauHinhIp',
        label: 'Cau hinh IP',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'cauHinhAnalog',
        label: 'Cau hinh Analog',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      {
        key: 'thucTrangIp',
        label: 'Thuc trang IP',
        type: 'number',
        required: true,
        defaultValue: 0,
        showInTable: true,
      },
      {
        key: 'thucTrangAnalog',
        label: 'Thuc trang Analog',
        type: 'number',
        required: true,
        defaultValue: 0,
      },
      { key: 'chuDauTu', label: 'Chu dau tu', type: 'text', maxLength: 200 },
      { key: 'namDauTu', label: 'Nam dau tu', type: 'number' },
      {
        key: 'duongTruyen',
        label: 'Duong truyen',
        type: 'select',
        codeKey: 'DUONG_TRUYEN_CAMERA',
      },
      { key: 'phanMem', label: 'Phan mem', type: 'text', maxLength: 200 },
      { key: 'luuTru', label: 'Luu tru', type: 'text', maxLength: 200 },
      { key: 'ghiChu', label: 'Ghi chu', type: 'text', maxLength: 2000 },
    ),
  },
};

export const BIZ_MODULE_LIST = Object.values(BIZ_MODULES);
